### ISSUE TITLE
Config file keywords?

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#1045]
@phlptp, in a recent conversation with Emily here at PNNL, she was looking for a way to set the log level from the config file and stumbled across the [Doxygen page for helics_definitions.hpp](https://helics.readthedocs.io/en/latest/doxygen/helics__definitions_8hpp.html). The flags sections seemed familiar in terms of config file options but she didn't see the keywords that defined log level. Should those be on this page somewhere? Also, is everything on this page usable as a config file keyword? If so, I'd like to reference it in the User Guide.

**Comment by phlptp** [comment]
That page describes the C++ versions of the internal flags.  To the best of my knowledge all have corresponding C/python versions.    I am going to work a little on improving the documentation specifically for logging but also some more on the configuration.

**Comment by trevorhardy** [comment]
Logging section has been updated for v3 release and I'm working on a Configuration Options Reference page that should cover this documentation need.

**Comment by trevorhardy** [comment]
Closing issue as now covered by #1499.
