### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by yingxuucf** [GMLC-TDC/HELICS#1048]
Did anyone met this error before?

(helics-environment) C:\pesgm-2019-helics-tutorial>python
Python 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 21:48:41) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import helics as h
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\helics-environment\lib\site-packages\helics.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\ProgramData\Miniconda3\envs\helics-environment\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\envs\helics-environment\lib\site-packages\helics.py", line 17, in <module>
    _helics = swig_import_helper()
  File "C:\ProgramData\Miniconda3\envs\helics-environment\lib\site-packages\helics.py", line 16, in swig_import_helper
    return importlib.import_module('_helics')
  File "C:\ProgramData\Miniconda3\envs\helics-environment\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: The specified module could not be found.
>>>

**Comment by kdheepak** [comment]
Can you try:

```
conda activate helics-environment # if you have already created the environment
conda uninstall helics
conda install -c gmlc-tdc helics
```

And share screenshots of the output?

**Comment by yingxuucf** [comment]
Thank you for response.
the output is as follows:

(helics-environment) C:\pesgm-2019-helics-tutorial>conda activate helics-environment

(helics-environment) C:\pesgm-2019-helics-tutorial>conda uninstall helics
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\ProgramData\Miniconda3\envs\helics-environment

  removed specs:
    - helics


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cycler-0.10.0              |           py37_0          13 KB
    freetype-2.9.1             |       ha9979f8_1         450 KB
    kiwisolver-1.1.0           |   py37ha925a31_0          53 KB
    mkl-service-2.3.0          |   py37hb782905_0         210 KB
    pyparsing-2.4.6            |             py_0          64 KB
    python-3.7.6               |       h60c2a47_2        14.8 MB
    pytz-2019.3                |             py_0         231 KB
    setuptools-44.0.0          |           py37_0         526 KB
    six-1.13.0                 |           py37_0          27 KB
    sqlite-3.30.1              |       he774522_0         627 KB
    wheel-0.33.6               |           py37_0          58 KB
    ------------------------------------------------------------
                                           Total:        17.0 MB

The following NEW packages will be INSTALLED:

  sip                pkgs/main/win-64::sip-4.19.8-py37h6538335_0

The following packages will be REMOVED:

  boost-cpp-1.68.0-h6a4c333_1000
  helics-2.0.0-py37h8c34e67_1
  libclang-9.0.1-default_hf44288c_0
  libsodium-1.0.17-h2fa13f4_0
  zeromq-4.3.2-h6538335_2

The following packages will be UPDATED:

  openssl            conda-forge::openssl-1.1.1d-hfa6e2cd_0 --> pkgs/main::openssl-1.1.1d-he774522_3

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    conda-forge::ca-certificates-2019.11.~ --> pkgs/main::ca-certificates-2019.11.27-0
  certifi                                       conda-forge --> pkgs/main
  cycler             conda-forge/noarch::cycler-0.10.0-py_2 --> pkgs/main/win-64::cycler-0.10.0-py37_0
  freetype           conda-forge::freetype-2.10.0-h563cfd7~ --> pkgs/main::freetype-2.9.1-ha9979f8_1
  icu                      conda-forge::icu-64.2-he025d50_1 --> pkgs/main::icu-58.2-ha66f8fd_1
  jpeg                   conda-forge::jpeg-9c-hfa6e2cd_1001 --> pkgs/main::jpeg-9b-hb83a4c4_2
  kiwisolver         conda-forge::kiwisolver-1.1.0-py37he9~ --> pkgs/main::kiwisolver-1.1.0-py37ha925a31_0
  libpng              conda-forge::libpng-1.6.37-h7602738_0 --> pkgs/main::libpng-1.6.37-h2a8f88b_0
  mkl-service        conda-forge::mkl-service-2.3.0-py37hf~ --> pkgs/main::mkl-service-2.3.0-py37hb782905_0
  pyparsing                                     conda-forge --> pkgs/main
  pyqt               conda-forge::pyqt-5.12.3-py37h6538335~ --> pkgs/main::pyqt-5.9.2-py37h6538335_2
  python               conda-forge::python-3.7.6-h5b45d93_2 --> pkgs/main::python-3.7.6-h60c2a47_2
  python-dateutil                               conda-forge --> pkgs/main
  pytz                                          conda-forge --> pkgs/main
  qt                      conda-forge::qt-5.12.5-h7ef1ec2_0 --> pkgs/main::qt-5.9.7-vc14h73c81de_0
  setuptools          conda-forge::setuptools-45.1.0-py37_0 --> pkgs/main::setuptools-44.0.0-py37_0
  six                        conda-forge::six-1.14.0-py37_0 --> pkgs/main::six-1.13.0-py37_0
  sqlite              conda-forge::sqlite-3.30.1-hfa6e2cd_0 --> pkgs/main::sqlite-3.30.1-he774522_0
  tornado            conda-forge::tornado-6.0.3-py37hfa6e2~ --> pkgs/main::tornado-6.0.3-py37he774522_0
  wheel                                         conda-forge --> pkgs/main
  wincertstore       conda-forge::wincertstore-0.2-py37_10~ --> pkgs/main::wincertstore-0.2-py37_0
  zlib               conda-forge::zlib-1.2.11-h2fa13f4_1006 --> pkgs/main::zlib-1.2.11-h62dcd97_3


Proceed ([y]/n)? y


Downloading and Extracting Packages
freetype-2.9.1       | 450 KB    | ############################################################################ | 100%
six-1.13.0           | 27 KB     | ############################################################################ | 100%
python-3.7.6         | 14.8 MB   | ############################################################################ | 100%
wheel-0.33.6         | 58 KB     | ############################################################################ | 100%
cycler-0.10.0        | 13 KB     | ############################################################################ | 100%
pytz-2019.3          | 231 KB    | ############################################################################ | 100%
sqlite-3.30.1        | 627 KB    | ############################################################################ | 100%
setuptools-44.0.0    | 526 KB    | ############################################################################ | 100%
kiwisolver-1.1.0     | 53 KB     | ############################################################################ | 100%
mkl-service-2.3.0    | 210 KB    | ############################################################################ | 100%
pyparsing-2.4.6      | 64 KB     | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(helics-environment) C:\pesgm-2019-helics-tutorial>python
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import helics as h
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'helics'
>>>

**Comment by kdheepak** [comment]
> helics-2.0.0-py37h8c34e67_1

Why is it installing v2.0.0? The latest version is v2.3.1: https://anaconda.org/gmlc-tdc/helics

Can you try creating a new environment and just installing helics?

```bash
$ conda create -n myhelicsenv python=3.7
$ conda activate myhelicsenv
$ conda install -c gmlc-tdc helics
```

**Comment by yingxuucf** [comment]
Thank you Kdheepak,
It is running in the new env. 
Now it is fixed. Thank you.
