### ISSUE TITLE
Remove VS2015 CI build after 2.4 release

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/HELICS#1053]
Remove the VS2015 CI build from Azure after the 2.4 release. The old Windows Server 2012 image on Azure Pipelines with VS2015 is going away on March 23, 2020 as announced in [this blog post](https://devblogs.microsoft.com/devops/azure-pipelines-hosted-pools-updates/).

After 2.4, tested support with VS2015 is being dropped because:
- The tests run slowly on the old image and tend to hit the timeout limit
- Newer VS versions don't depend much on the OS
- Windows is pretty good with backwards compatibility (e.g. release builds will likely work on older versions)

**Comment by phlptp** [comment]
It looks like we will still have appveyor for VS2015 builds for a while yet.  I was thinking we might switch that to use cygwin, but it might be better to leave it as a 2015 compile test.

**Comment by nightlark** [comment]
Information on usage of Cygwin (vs MSYS2/MinGW) and VS2015 would be nice. I'd guess that both Cygwin and VS2015 have very few users -- and that Cygwin uses are covered by VS, MSYS2, or WSL (any cases where Cygwin must be used?).

**Comment by phlptp** [comment]
The only possible case I heard was someone trying to get NS3 working on windows and didn't have access to WSL, so they were using cygwin.    Not entirely clear if NS3 compiles on MSYS2 or not and how hard it would be to link NS3 with HELICS on MSYS2.    But I agree, there are likely very few users of VS2015 anymore.

**Comment by phlptp** [comment]
Can this be closed?

**Comment by nightlark** [comment]
The linked PR getting merged should've closed it.
