### ISSUE TITLE
automated formatting of cmake files

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#1078]
We already do automated formatting of the C++ and hpp files.  It would be nice if we could do the same with the cmake files to keep everything clean and consistent.

We have cmake format but it currently depends on someone running that regularly and pushing it.  automating it would save some time.

**Comment by nightlark** [comment]
I think the formatting should be limited to indentation, unlike with clang-format, cmake_format can make changes that break things.

Or an alternative to cmake_format that format things while ensuring it still works the same way.

**Comment by phlptp** [comment]
Other than that one issue with the long strings, what other problems have we encountered.  I have run the cmake-format a number of times on most of the cmake code, and apart from the one issue we encountered haven't had any issues.

**Comment by nightlark** [comment]
I think it's just the long strings -- I don't really trust it to not break things if it's allowed to change where line breaks within a command happen.

**Comment by phlptp** [comment]
I would expect a level of code review and CI tests to catch most if not all of the potential issues.

**Comment by nightlark** [comment]
It looks like setting line_width to some large number would probably keep it from happening and still format functions with lots of arguments in a vertical layout -- that would make it work with the 3 instances currently using `# cmake-format: off` without breaking a long string or a string arg that ends up too close to the end of the line cut-off.

Do we want it to create PRs like the clang-format action does? Would we want to have a combined formatting action that opens a single formatting PR with two separate commits?
