### ISSUE TITLE
Using `timeDelta` in json file doesn't work

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#1138]
**receiver.json**

```json
{
  "coreType": "zmq",
  "loglevel": 7,
  "name": "receiver",
  "subscriptions": [
    {
      "global": true,
      "key": "topicA",
      "required": true,
      "type": "double"
    }
  ],
  "timeDelta": 0.5
}
```

**sender.json**

```json
{
  "coreType": "zmq",
  "loglevel": 7,
  "name": "sender",
  "publications": [
    {
      "global": true,
      "key": "topicA",
      "required": true,
      "type": "double"
    }
  ],
  "timeDelta": 1.0
}
```

**receiver.py**

```python
# -*- coding: utf-8 -*-
import os
import helics as h

fed = h.helicsCreateCombinationFederateFromConfig(
    os.path.join(os.path.dirname(__file__), "receiver.json")
)

topicA = h.helicsFederateGetSubscription(fed, "topicA")

h.helicsFederateEnterExecutingMode(fed)
currenttime = 0
for t in range(5, 10 + 1):
    while currenttime < t:
        currenttime = h.helicsFederateRequestTime(fed, t)
        t = h.helicsInputGetDouble(topicA)
        print(f"Received t = {t} at time = {currenttime}")

h.helicsFederateFinalize(fed)
h.helicsFederateFree(fed)
h.helicsCloseLibrary()
```

**sender.py**

```python
# -*- coding: utf-8 -*-
import os
import helics as h

fed = h.helicsCreateCombinationFederateFromConfig(
    os.path.join(os.path.dirname(__file__), "sender.json")
)

topicA = h.helicsFederateGetPublication(fed, "topicA")

h.helicsFederateEnterExecutingMode(fed)

currenttime = 0

for t in range(5, 10 + 1):
    while currenttime < t:
        currenttime = h.helicsFederateRequestTime(fed, t)
    print(f"Sending t = {t} at time = {currenttime}")
    h.helicsPublicationPublishDouble(topicA, t)

h.helicsFederateFinalize(fed)
h.helicsFederateFree(fed)
h.helicsCloseLibrary()
```

## Expected

```
Received t = 0.0 at time = 5.0
Received t = 5.0 at time = 5.5
Received t = 6.0 at time = 6.0
Received t = 6.0 at time = 7.0
Received t = 7.0 at time = 7.5
Received t = 7.0 at time = 8.0
Received t = 8.0 at time = 8.5
Received t = 8.0 at time = 9.0
Received t = 9.0 at time = 9.5
Received t = 9.0 at time = 10.0
```

## Actual

```
Received t = 0.0 at time = 5.0
Received t = 5.0 at time = 5.000000001
Received t = 5.0 at time = 6.0
Received t = 6.0 at time = 6.000000001
Received t = 6.0 at time = 7.0
Received t = 7.0 at time = 7.000000001
Received t = 7.0 at time = 8.0
Received t = 8.0 at time = 8.000000001
Received t = 8.0 at time = 9.0
Received t = 9.0 at time = 9.000000001
Received t = 9.0 at time = 10.0
```

If I run without using a JSON config and programmatically create the `FederateInfo` and set it using the following:

```
h.helicsFederateInfoSetTimeProperty(fedinfo, h.helics_property_time_delta, 0.5)
```

it works as expected.

**Comment by phlptp** [comment]
I don't think we support camelCase for any of the properties in json/toml files.  right now "time_delta" or "timedelta" would work.    Do you think we should support Camelcase as well for all the properties/flags?

**Comment by nightlark** [comment]
One of the tests uses timeDelta and coreType, and most of the examples in the user guide do the same thing -- though I think they're just using default values so no issues were noticed?
https://github.com/GMLC-TDC/HELICS/blob/master/tests/helics/test_files/Control_test.json
https://github.com/GMLC-TDC/HELICS/blob/master/examples/user_guide_examples/Example_1b/Transmission/Transmission_json.json

**Comment by phlptp** [comment]
I guess the question is do we want to generally allow camelCase Support in the config files.  I think the command line does for the most part already.

**Comment by nightlark** [comment]
Are there any downsides to supporting camelCase, or making the json field names case insensitive?

**Comment by phlptp** [comment]
General case insensitivity would be a major change in how things are handled.  Could be done I suppose but would be a major change. 

camelCase  support would involved adding some additional checks.  So slightly bigger executable, and slight increase in processing time for files.

**Comment by kdheepak** [comment]
I don't think we should support case insensitive configuration. I also think we should have one and only one obvious way to do it, e.g. always `lowercase` or always `snake_case`. Supporting both `lowercase` and `snake_case` seems like a cause for confusion. For example, if I have a large set of configuration files and I'm searching through them for `time_delta` and find a few and change them. But I may not know to search for `timedelta`. I think the reason I'm saying this is that it seems to violate some expectation of time when I'm working with the content of files in the command line.

**Comment by phlptp** [comment]
How about we add camelCase for now.  By release 2.5 we figure out which format we want to standardize on(meaning next two weeks),   I will figure out how to generate a warning on others from 2.5 onward.  Then in 3.0 we can remove support for them in some fashion.

**Comment by nightlark** [comment]
Case sensitivity seems to be less of an issue for other JSON libraries than handling both snake_case and lowercase/camelCase style names.

**Comment by phlptp** [comment]
I will open a new issue at somepoint soon about discussion which "flag" name format we want to finalize on for 3.0
