### ISSUE TITLE
Which federate is still connected?

### ISSUE THREAD

**Issue by nadiavp** [GMLC-TDC/HELICS#1167]
When debugging my HELICS federate setup it would be helpful to know which federates are still connected and the sequence in which they disconnect. 

Beyond having the helicsBrokerIsConnected(helics_broker broker) function which tells if there are any federates still connected to the broker, it would be nice to have a call that lists which federates the broker is connected to in order to make sure that federates are disconnecting successfully and at the appropriate time.

**Comment by phlptp** [comment]
You will want to take a look at the [queries](https://helics.readthedocs.io/en/latest/user-guide/queries.html)  interface.  There are some queries that might give you the answers you are looking for.   Particularly `federation_state`   These are all pretty new so you need a newer release of HELICS to have them available.  And if you have suggestions for other queries that would be useful or improvements please let us know.

**Comment by phlptp** [comment]
I am going to close this issue.  If there is more suggestions or other needed details feel free to open a new one.
