### ISSUE TITLE
Change order in `helics_error_types`

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#1193]
**Describe the bug**

https://github.com/GMLC-TDC/HELICS/blob/e80b64f41d0ec3836b33d1af1f5b9b2094b3fa93/src/helics/helics_enums.h#L149-L171

Current ordering for `helics_error_types` is highest to lowest based on value of the enum. This causes errors in code generation for nim.

**What is the expected behavior?**

Typically C enum's are ordered lowest to highest. All other enum's in the code base are ordered lowest to highest.

**Comment by phlptp** [comment]
I think in this case it generally went in magnitude order, but I suppose it could be reordered so helics_ok is at the end.
