### ISSUE TITLE
Add query to get version of helics shared library in another federate

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#1283]
It would be useful to query the version of the helics library to make sure that all the federates in a cosimulation are using the same version of the library.

**Comment by phlptp** [comment]
I think the query is a good idea.  

It isn't strictly required that all federates use the same library version.  They are for the most part binary compatible.

**Comment by kdheepak** [comment]
Agreed. I think if a user accidentally is using different versions when
they didn't intend to, this can be used to notify them.
