### ISSUE TITLE
libJNIhelics.so was not built

### ISSUE THREAD

**Issue by xcosmos6** [GMLC-TDC/HELICS#1285]
I tried to build helics on Ubuntu 18.04 with the lastest master but libJNIhelics.so was not built with the following config:

cmake -DBUILD_PYTHON_INTERFACE=ON -DBUILD_JAVA_INTERFACE=ON -BUILD_SHARED_LIBS=ON -DJAVA_AWT_INCLUDE_PATH=NotNeeded -DHELICS_DISABLE_BOOST=ON -DCMAKE_INSTALL_PREFIX=$TESP_INSTALL -DCMAKE_BUILD_TYPE=Release ..

Then I tried the Mar 27 commit 815e7d1, it didn't have it neither. I know the Feb 11 version had it.

I do see the libhelicsJava.so and libhelicsSharedLib.so.2.4.1 though.

Would you please take a look on this? Thank you very much!

**Comment by nightlark** [comment]
From the Feb 25 commit 3a226830, I think libhelicsJava.so is what you're looking for.

**Comment by xcosmos6** [comment]
> From the Feb 25 commit [3a22683](https://github.com/GMLC-TDC/HELICS/commit/3a226830e0b96cd06e13fe7488175c41caed6132), I think libhelicsJava.so is what you're looking for.

I see. Thank you.
