### ISSUE TITLE
Missing C API Function Documentation

### ISSUE THREAD

**Issue by afisher1** [GMLC-TDC/HELICS#1321]
* **I'm submitting a ...**
  - [ ] bug
  - [ ] feature request
  - [x] support question

### Feature Request / Support Question

The C API Reference on HELICS readthedocs page is missing the following function documentation

from helics.h:
- helicsErrorInitialize
- helicsErrorClear
- helicsBrokerMakeConnections
- helicsCoreWaitForDisconnect
- helicsCoreMakeConnections
- helicsCoreGetAddress
- helicsCoreConnect
- helicsFederateInfoSetBrokerInitString
- helicsFederateInfoSetBrokerKey
- helicsFederateGlobalError
- helicsFederateLocalError
- helicsFederateEnterInitializingModeCompleted
- helicsFederateRequestTimeAdvance
- helicsFederateAddDependency
- helicsFederateSetLogFile
- helicsFederateLogErrorMessage
- helicsFederateLogWarningMessage
- helicsFederateLogInfoMessage
- helicsFederateLogDebugMessage
- helicsFederateLogLevelMessage
- helicsCoreSetLogFile
- helicsBrokerSetLogFile
- helicsQueryExecuteCompleted

from helicsCallbacks.h
- helicsBrokerSetLoggingCallback
- helicsCoreSetLoggingCallback
- helicsFederateSetLoggingCallback
- helicsFilterSetCustomCallback

from MessageFederate.h
- helicsEndpointIsValid
- helicsEndpointSendMessageObject
- helicsEndpointSendMessageObjectZeroCopy
- helicsEndpointGetMessageObject
- helicsFederateGetMessageObject
- helicsFederateCreateMessageObject
- helicsFederateClearMessages
- helicsEndpointClearMessages
- helicsMessageGetSource
- helicsMessageGetDestination
- helicsMessageGetOriginalDestination
- helicsMessageGetOriginalSource
- helicsMessageGetTime
- helicsMessageGetString
- helicsMessageGetMessageID
- helicsMessageCheckFlag
- helicsMessageGetRawDataSize
- helicsMessageGetRawData
- helicsMessageGetRawDataPointer
- helicsMessageIsValid
- helicsMessageSetSource
- helicsMessageSetDestination
- helicsMessageSetOrginalSource
- helicsMessageSetOriginalDestination
- helicsMessageSetTime
- helicsMessageResize
- helicsMessageReserve
- helicsMessageSetMessageID
- helicsMessageClearFlags
- helicsMessageSetFlagOption
- helicsMessageSetString
- helicsMessageSetData
- helicsMessageAppendData
- helicsMessageCopy

from MessageFilters.h
- helicsFilterIsValid

from ValueFederate.h
- helicsFederateClearUpdates
- helicsFederateRegisterFromPublicationJSON
- helicsFederatePublishJSON
- helicsPublicationIsValid
- helicsInputIsValid
- helicsInputGetInjectionUnits
- helicsInputGetExtractionUnits
- helicsPublicationSetMinimumChange
- helicsInputSetMiniumChange
- helicsInputClearUpdate

**Comment by nightlark** [comment]
I think it's this file that needs updating: https://github.com/GMLC-TDC/HELICS/blob/master/docs/c-api-reference/index.md

**Comment by kdheepak** [comment]
This is resolved in the `develop` branch of the documentation.

https://docs.helics.org/en/develop/c-api-reference/index.html
