### ISSUE TITLE
Missing Setters in C++98 Message Class

### ISSUE THREAD

**Issue by afisher1** [GMLC-TDC/HELICS#1322]
**Is your feature request related to a problem? Please describe.**
Currently the helics_message struct is deprecated and will be removed in 3.0 of helics. Instead the helics_message_object is to be used. The C++98 exposed the helics_message_object as the Message class. The Message class is missing setter functions for size, data, and c_str. This can currently only be resolved by using the C API to populate a helics_message_object struct and then provide that to the Message constructor. However, It would be nice to be able to construct a Message class without having to use the C API even though it provides complete access to it underneath the hood.

**Describe the solution you'd like**
I would like to have setter functions to mirror the Message class's data(), size(), and c_str() getters. 

**Describe alternatives you've considered**
Don't use the Message class as there are other functions that don't require a Message class as input when trying to send a message through endpoints.

**Comment by phlptp** [comment]
@afisher1 I merged this in and will close the issue but when you get a chance take a look and make sure I didn't miss anything.
