### ISSUE TITLE
All string translations are JSON?

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#1368]
One possible change for HELICS 3 would be making all queries and string conversions to something else be valid json objects.    The biggest change is probably quoting strings and string vectors,  but it would allow more obvious translations to external languages and be more contextually easy to explain.  
many existing queries already return json, so having them all return valid json may simplify some things.  

The most annoying on might be complex vectors as I don't think Json supports complex numbers directly.  

@nightlark @trevorhardy @kdheepak @eberleim

**Comment by trevorhardy** [comment]
I like the idea of queries always returns structured data (JSONs in this case). 

And regarding the complex numbers, it looks like Python has a pretty easy way to convert strings to complex values so we might be able to squeeze it in that way.

**Comment by nightlark** [comment]
Queries returning JSON seems better than coming up with our own format, and there are standard libraries in other languages that make working with JSON easy -- though we should aim to make it conform to  the JSON standard (RFC 7159) to avoid issues with non-standard additions like comments.

What would string conversions to something else affect? Something like a `complexFromString` function that takes a string as input?

**Comment by phlptp** [comment]
I am guessing the changes would be 
-  queries returning single strings need to be quoted
-  queries returning string vectors will be modified to meet json standard
-  vector to string would likely be modified slightly
- complex to string ?
- complex vector to string? 

The last two might require some thought as there are likely a couple different ways that could be done.  

As far as supporting comments the only place I think we really need it is in the config file support

**Comment by nightlark** [comment]
Okay. Having the returned string be something (JSON-friendly?) that can be turned into valid JSON by adding `[]` or quotes around it seems more natural than needing to remove them.

**Comment by kdheepak** [comment]
I'm supportive of having json be returned as part of the queries. Right now custom parsing is required to deal with this. If we are returning structured data, we might as well use a standard format.
