### ISSUE TITLE
Improve installation process documentation 

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#1369]
The [current installation page](https://docs.helics.org/en/latest/installation/index.html) provides several alternative ways of installing HELICS with little guidance on which one is most appropriate for a given user's needs. These needs range from using specific Python versions, using specific tools (GridLAB-D, FESTIV, GridDyn, etc), using specific OSs (and versions of said OS) and/or using specific compilers. 

For v3, I would like to improve the Installation documentation to help users quickly figure out the most appropriate installation method and guide them through that process as best we can.

I can do whatever writing is necessary but I need input on how we should structure things. What determines how a user should do an install? What use cases, applications, or complementary software packages are critical for managing this right now?

**Comment by trevorhardy** [comment]
I just had a thought: it would be very helpful if we could find a good resource we could like to on managing environments (is this a thing on Windows?) I think it would be helpful to include this on the installation page. I know I have been bit by conflicting requirements from different packages (HELICS requires v3 of something and packageA requires v2 of the same thing) and knowing from the start how to deal with this could be very helpful to users (like me) that don't often have to manage this and don't have a good system already in place.

**Comment by trevorhardy** [comment]
@ELBarrett will be taking point on this for the documentation team. I'm unassigning the rest of those I added to make it clear who is leading the task.

**Comment by trevorhardy** [comment]
Ideally, the flow-chart I'm envisioning would not only allow users to figure out what installation they need but also how to upgrade their installation as their needs change. For example, they may start out with Python-only federations and did an install with Conda. Now, though, they need to add a C++ federate and need to know the best way to get the appropriate libraries installed and built so they have a sufficient HELICS installation to support their needs.

**Comment by nightlark** [comment]
What about writing something in js that let's them check off what they want (+ maybe what they have installed) that then gives them what steps are needed to get the additional libraries? It could be easier to add new options than a static image.

**Comment by trevorhardy** [comment]
Committed to the helics3userguide branch.
