### ISSUE TITLE
Improved API documentation via LibClang

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#1370]
After discussion with @nightlark and @kdheepak, we are proposing the use of LibClang to allow the creation of automatic API documentation for Python, Julia, Nim, and perhaps others. Doing so will allow Integrators and Developers easier understanding of the APIs in their language without having to guess at the function names and datatypes expected for the API in their language. 

This documentation generation would be run as a part of the CI job and thus would update the "readthedocs" page automatically as well.

**Comment by trevorhardy** [comment]
I'm hopeful that @afisher1 and/or @eberleim would be able to help out with this in the coming weeks.

**Comment by trevorhardy** [comment]
@phlptp, what is the relationship between this and what you're discussing in #1339?

**Comment by kdheepak** [comment]
I have an initial version working that autogenerates the documentation using LibClang. Let me know if anyone is interested in working on taking this further, I can provide the current code + outline for going forward + more information.

**Comment by trevorhardy** [comment]
@afisher1 is taking this on and depending on his health, we're aiming to get Python API documentation in place for v3.

**Comment by trevorhardy** [comment]
We've made a slight shift in strategy. @afisher is going to be using LibClang to start work on a custom Python API. We don't expect this to be finished by v3 release. Once the custom API is done, automated generation of API documentation will be very straight-forward.

In the mean time, @eberleim is going to be working on a custom Python API documentation for release by v3. This will be documentation of the SWIG-generated interface (including its imperfections). We expect this will be a moderate lift and serve as a bridge until @afisher1's work on the new API is done.
