### ISSUE TITLE
helicsPublicationPublishString() intermittently fails on TCP core on Linux

### ISSUE THREAD

**Issue by vbarsuk** [GMLC-TDC/HELICS#1380]
**Describe the bug**
On intense traffic helicsPublicationPublishString() can fail on TCP core on Linux.

python: /........./helics/helics_2.5/HELICS-src/src/helics/network/tcp/TcpHelperClasses.cpp:282: size_t helics::tcp::TcpConnection::send(const string&): Assertion `sz == dataString.size()' failed.

on debug run sz value was 30, dataString.size() was 4222
With Linux it is possible to get a successful partial write into TCP socket in async mode.

**What is the expected behavior?**
 send() should not fail on assert() with partial write

**To Reproduce**
Keep  publishing of large strings

**Environment (please complete the following information):**
 
Happened on helics 2.5 but I believe many other versions can be affected.
Environment: CentOS Linux release 7.4.1708 (Core)
```
$ helics_app --version
```

**Additional context and information**
I believe it is a exclusive behavior of TCP sockets on Linux. I never saw such a behavior on Windows or any other system.
I was analyzing the source code when found the issue and I was able to reproduce the issue under the load.

In TcpHelperClasses.cpp in send() , mere assert() is not sufficient.

**Comment by phlptp** [comment]
So is the issue that the return from the TCP send call can on occasion return a value less then requested?  In which case did it not send it send a partial packet and we should send the rest or treat that as a failure and try again?    

I agree on the assertion, the question is what should be done in that case.   check partial success and try again on the part that wasn't sent?

**Comment by vbarsuk** [comment]
Yes.
With Windows and other unix systems send() either sends nothing or everything. According to specs it still can send a partial buffer.
I saw this behavior on Linux only.
I would keep sending the rest of the buffer in the loop till it is completely sent.
I will work on the solution if it is ok with you.

Slava

**Comment by phlptp** [comment]
If you have a good understanding of how to fix it a PR would be welcome.

**Comment by phlptp** [comment]
@vbarsuk I know you were working on a PR,  what is the status and any chance it would be ready by the end of the week or early next at the latest.  Otherwise would get it into 2.6.1 release.
