### ISSUE TITLE
Web interface message table?

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#1430]
The prototype web interface @eberleim put together has tables for federates and for publications (which, I'm realizing, needs to encompass directed outputs as well) but what about messages? Those are a fundamentally different interaction and I think they'll need their own table.  And that table may need to be more detailed; for example:

- Sender
- Sender endpoint name (could be combined with Sender field)
- Simulated time of transmission
- Payload (value)
- Receiver
- Receiver endpoint name
- Simulated reception time
- Payload (value)

I think the extra columns are needed since messages take time to travel, have the possibility of not making to their receiver, and could be altered _en route_. This means some of those fields will be blank for some of the time which I think is OK.  This gets complicated, though.

Thoughts?

**Comment by eberleim** [comment]
@trevorhardy This raises an interesting question I need more context on: Is it even possible for the observer federate to view these directed messages without adding some kind of man-in-the-middle infrastructure in HELICS to allow access? 
My (admittedly limited) understanding was that the observer federate @kdheepak is implementing essentially subscribed to all available publications, allowing it to monitor them all. 
I'm not sure it can see messages which specifically identify their destination federate.

**Comment by trevorhardy** [comment]
@eberleim, yes it is possible but does use a different mechanism. One of the "filters" that can be installed at endpoints is a "clone" filter that would make a duplicate message which we could send to the observer. Entirely different mechanism and extra work but very possible. Given this extra work, maybe we don't prioritize it for the initial v3 release?

**Comment by eberleim** [comment]
Rather than trying to do it manually, we'd probably want infrastructure to automatically clone all messages to the observer when running from helics-cli. That might be more of a lift than is reasonable for v3.

**Comment by trevorhardy** [comment]
This issue is being closed out here and moved to the helics_cli repo.

**Comment by trevorhardy** [comment]
https://github.com/GMLC-TDC/helics-cli/issues/17
