### ISSUE TITLE
Auto-generated documentation not displaying movie correctly

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#1431]
**Describe the bug**
The following Markdown page references a movie file that is not rendering properly when the page/documentation is auto-generated:

[https://docs.helics.org/en/v3userguide/user-guide/web_interface.html](https://docs.helics.org/en/v3userguide/user-guide/web_interface.html)

**What is the expected behavior?**
I'm assuming that the same linking structure for images would have worked for movies; I could easily be wrong about this.

**Environment (please complete the following information):**
Checked on my Mac with Safari, Chrome, and Firefox. All render it differently and all not in a way I expected.

**Comment by nightlark** [comment]
It would be better to upload the movie to YouTube and embed the player. Binary files like movies and images can get pretty big and they don't work very well with git -- it can't compress them much and if a change is made, it has trouble with generating a diff so it will just add a whole extra copy to the image. End result is that cloning the code will take longer.

If possible it would be better to find a place outside the repository to put them (some other projects on github create an issue and upload images as attachments) and then link to that location (or we could add a step to the RTD build that downloads the images).

Actually, the other solution  is git lfs (large file storage), for which GitHub provides ~1gb of storage free for each organization, though there could be bandwidth limits, and it looks like getting it working on RTD is a bit tricky.

**Comment by trevorhardy** [comment]
Good suggestions, @nightlark. I'll just assume for now that I don't put the movie in the repo and if I plan on putting screencasts in the User Guide I will host them externally and embed them like you suggested.
