### ISSUE TITLE
Add User Guide chapter on broker server

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#1481]
There is currently no documentation on the use of the broker server and if this is a supported feature it should be added.

**Comment by phlptp** [comment]
See https://docs.helics.org/en/latest/user-guide/webserver.html
and
https://docs.helics.org/en/latest/user-guide/simultaneous_cosimulations.html

For some docs on the broker_server

**Comment by trevorhardy** [comment]
Updated and integrated into the v3 User Guide release.
