### ISSUE TITLE
no python api for setting log level

### ISSUE THREAD

**Issue by bearcub** [GMLC-TDC/HELICS#1484]
In the user guide examples:
/examples/user_guide_examples/Example_1a

```
h.helicsFederateInfoSetLoggingLevel(fedinfo, 1)
```

throws the following error:

```
AttributeError: module 'helics' has no attribute 'helicsFederateInfoSetLoggingLevel'
```

We think that would have been in HELICS 2.?

Is there an existing way to set the log level in the C api in python?

**Comment by nightlark** [comment]
Try using `h.helicsFederateInfoSetIntegerProperty(fedinfo, h.helics_property_int_log_level, 1)`

https://docs.helics.org/en/latest/user-guide/logging.html has some more information on using logging that I think should also apply to the language interfaces that use the C API.
