### ISSUE TITLE
`h.helicsFederateGetPublicationByIndex` is broken in python

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#1492]
**Describe the bug**

`h.helicsFederateGetPublicationByIndex` returns the incorrect value in python.

~~`h.helicsFederateGetPublicationByIndex` throws an error in julia.~~

**Environment (please complete the following information):**

- Operating System: [Mac]
- Language Extension: [Python]
- `conda install -c gmlc-tdc helics`
- HELICS version: 2.5.2 (2020-06-14)

**To Reproduce**

Please provide a minimal working example of the bug if possible.

[Archive.zip](https://github.com/GMLC-TDC/HELICS/files/4957626/Archive.zip) that contains all julia, python and json files.

This is the json file being used.

```json
{
    "name": "fed_1",
    "loglevel": 7,
    "coreType": "zmq",
    "period": 0.25,
    "uninterruptible": false,
    "wait_for_current_time_update": false,
    "publications": [
        {
            "global": true,
            "key": "value_1",
            "type": "complex"
        }
    ],
    "subscriptions": [
        {
            "required": true,
            "key": "value_2",
            "type": "complex"
        }
    ]
}
```

If I run the following code:

```python
import helics as h
import cmath
import time
import re
import sys

def create_broker():
    initstring = "--federates=1 --name=mainbroker --loglevel=6"
    broker = h.helicsCreateBroker("zmq", "", initstring)
    isconnected = h.helicsBrokerIsConnected(broker)
    if isconnected == 1:
        pass
    return broker

def destroy_federate(fed):
    h.helicsFederateFinalize(fed)
    while (h.helicsBrokerIsConnected(broker)):
        time.sleep(1)
    h.helicsFederateFree(fed)
    h.helicsCloseLibrary()


if __name__ == "__main__":
    broker = create_broker()
    fed = h.helicsCreateValueFederateFromConfig('fed1.json')
    status = h.helicsFederateRegisterInterfaces(fed, 'fed1.json')
    pubkeys_count = h.helicsFederateGetPublicationCount(fed)
    subkeys_count = h.helicsFederateGetInputCount(fed)
    pubid = {}
    for i in range(0, pubkeys_count):
        pubid[f"m{i}"] = h.helicsFederateGetPublicationByIndex(fed, i)
        pubtype = h.helicsPublicationGetType(pubid[f"m{i}"])
        pub_key = h.helicsPublicationGetKey(pubid[f"m{i}"])
        print("pubid: ", pubid[f"m{i}"])
        print("pubtype: ", pubtype)
        print("pub_key: ", pub_key)

    destroy_federate(fed)
```

This is the output I get

```
pubid:  <Swig Object of type 'helics_input' at 0x7fe252b55120>
pubtype:  complex
pub_key:  value_1
```

**Comment by phlptp** [comment]
I am not totally clear what the error is.  What did you expect as a result?

**Comment by phlptp** [comment]
@kdheepak can you elaborate on what the error is here.  as far as I can tell you created one publication and one publication was listed when you printed it?

**Comment by kdheepak** [comment]
It's supposed to print out a publication, right? It's printing out a pointer to an `helics_input` object.

**Comment by phlptp** [comment]
hmmm, I will check

**Comment by phlptp** [comment]
@kdheepak  can you run a check and add a call to helicsPublicationIsValid to check if it is valid publication.  
The possibility exists that python doesn't distinguish between helics_input and helics_publication since they are exactly the same C type  both are a `void *`

**Comment by kdheepak** [comment]
Okay, I'll check that.

**Comment by phlptp** [comment]
@kdheepak  any update on this issue?

**Comment by kdheepak** [comment]
Calling `helicsPublicationIsValid` returns `1`.

**Comment by kdheepak** [comment]
I tried the same with the new python api, and I get the same error that I get in Julia (issue is linked above). So this issue is related to swig python interface.

**Comment by kdheepak** [comment]
I think the reason this breaks is that the code is called `fed = helicsCreateValueFederateFromConfig("fed1.json")` AND `helicsFederateRegisterInterfaces(fed, "fed1.json")`. 

The user should either 

1. Call only `fed = helicsCreateValueFederateFromConfig("fed1.json")`. This registers all publications and inputs defined in the json file. They should not call `helicsRegisterInterfaces` in this case.
2. Create a `ValueFederate` programmatically, i.e.:

```python
fedinfo = h.helicsCreateFederateInfo()
h.helicsFederateInfoSetCoreTypeFromString(fedinfo, "zmq")
fed = h.helicsCreateValueFederate("fed_2", fedinfo)
```

and then call `helicsRegisterInterfaces(fed, "fed1.json")`.
