### ISSUE TITLE
Deprecate configuration options valid strings for single option

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#1499]
Most configuration options (JSON and command-line) have multiple supported strings that are interchangeable and refer to the same option in the source code. One of the worst offenders is:

`strict_type_matching`
`strict_type_checking`
`strict_input_type_matching`
`strict_input_type_checking`
`strictinputtypechecking`
`strictinputtypematching`
`stricttypechecking`
`stricttypematching`
`strict`

The well-intentioned efforts to be broad in supporting a variety of terms can lead to a potential source of confusion; is `strict` the same as `strict_type_matching` or, perhaps, does `strict` refer to some other check that can be implemented? 

In an effort to reduce this confusion, I propose that we change the supported list of strings in the following way:

1. Only one term will be used per option. Using the above example, we will refer to this as "strict type checking" and remove all strings that use the term "matching" (or vice versa).
2. We will continue to support the three casing styles for that term: `strict_type_checking`, `strictTypeChecking`, and `stricttypechecking`. For terms that don't currently support all three styles the missing versions will be added.
3. The preferred term will be derived from the corresponding API name when applicable.

As this will be a breaking change for some existing JSON config files and scripts using command line options, the goal would be to roll this into the v3 release.

All input is welcome but we should probably make this change soon so somebody (likely @trevorhardy or somebody he can con into this) can get these changes made.

**Comment by trevorhardy** [comment]
Given no further comments on this, I'm going to (perhaps temporarily) assign to myself the task of making definitive decisions on the terminology used for these options and work with the developers to update the code. I'm hoping/assuming that I'll be able to make these changes myself (since its largely just literal string editing in the code base) but I'll check with them to make sure there aren't any surprises.

Once I have a list of changes I'll be making I'll post them here before actually editing the code.

**Comment by phlptp** [comment]
@trevorhardy  can you make a list of all the strings that you remove.  
My current thinking is there is likely to be a 2.7 release, whose main purpose is to deprecate things and provide a compatibility layer.  In that release I would probably put a chunk of code that will catch some of those options and create a warning to users.

**Comment by trevorhardy** [comment]
@phlptp - Sure, I don't know if I'm going to to starting on this today but I'll work towards getting you that last ASAP.

**Comment by phlptp** [comment]
I wouldn't do this for at least 3 weeks, so no rush,  just keep a record.

**Comment by trevorhardy** [comment]
As best as I can tell, I've found all the synonyms and have established the following list of supported terms; those that are previous synonyms are showing below the preferred term indented. If I've missed any, let me know.

```
First set of entries is the new canonical term. Terms indented beneath the set are being deprecated in v3.

core_type, coretype, coreType
     type

core_init_string, coreinitstring, coreInitString
    coreinit

broker_init_string, brokerinitstring, brokerInitString
    brokerinit

source_only, sourceonly, sourceOnly
    source
    
wait_for_current_time_update, waitforcurrentimeupdate, waitForCurrentTimeUpdate
    delayed_update
    delayedUpdate
    wait_for_current_time
    
restrictive_time_policy, restrictivetimepolic, restrictiveTimePolicy
    conservative_time
    conservative_time_policy
    conservativeTime

slow_responding, slowresponding, slowResponding
    slow
    no_ping
    disable_ping

max_iterations, maxiterations, maxIterations
    iterations
    
noack_connect, noackconnect, noackConnenct
    noack

use_os_port, useosport, useOsPort
    osport
    
local_interface, localinterface, localInterface
    interface

local_port, localport, localPort
    interfaceport
    
connection_required, connectionrequired, connectionRequired
    required
    
input_priority_location, inputprioritylocation, inputPriorityLoction
    priority
    priority_location
    input_priority
    
clear_priority_list, clearprioritylist, clearPriorityList
    clear_priority
    
single_connection_only, singleconnectiononly, singleConnectionOnly
    single
    single_connection

multiple_connections_allowed, multipleconnectionsallowed, multipleConnectionsAllowed
    multipe_connections
    multiple

multi_input_handling_method, multiinputhandlingmethod, multiInputHandlingMethod
    multi_input_handling

reroute
    redirect
    
delay
    timedelay
    time_delay
    time delay
    
random_delay, randomdelay, randomDelay
    random delay

random_drop, randomdrop, randomDrop
    random delay
    
clone
    cloning
    


```

**Comment by trevorhardy** [comment]
Changes made and live as a part of the v3 release versions
