### ISSUE TITLE
Add API support for force_logging_flush and dumplog

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#1500]
I don't know the level of effort involved but if it is small, I propose the addition of enumerated values to allow the use of helicsFederateInfoSetIntegerProperty() to set or clear `force_logging_flush` and `dumplog`. I've tentatively assigned this to v3 but I would consider this a low-priority request.

**Comment by phlptp** [comment]
Would this be better as a flag property vs an int property.  Int properties are ones with integer values like logging or the max iterations.  I am not seeing more than a binary value for these?

**Comment by trevorhardy** [comment]
Ahh, good point. Yeah, I think these would be flag properties.
