### ISSUE TITLE
Connection info messages

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#1537]
It is becoming clear one common issue with setting up a HELICS co-simulation is that in the early going something isn't moving forward as expected.  This can be for any number of reasons most of them pretty simple to fix, but figuring out the issue is proving somewhat more complex.  

What I am proposing is a message generation that would occur if a federate is waiting for a specified period of time in any of the blocking calls.  This message would print out the current status and some information about which federate is causing the delay if possible.  This information might be helpful in diagnosing the cause of the delay.

**Comment by trevorhardy** [comment]
I like this idea. I think getting the messages right will take some iteration but I think its a step in the right direction.

**Comment by trevorhardy** [comment]
@phlptp, you've got this one covered in v3.1, right?

**Comment by phlptp** [comment]
Timeouts were added a while ago, so I think this can be closed
