### ISSUE TITLE
can a getCurrentTime function get added to cpp98 Federate.hpp?

### ISSUE THREAD

**Issue by xcosmos6** [GMLC-TDC/HELICS#1542]
Hi,

Is it possible to add a getCurrentTime function in the Federate.hpp in the cpp98 wrapper? Something like:

`helics_time getCurrentTime() const
{
     return helicsFederateGetCurrentTime(fed, HELICS_NULL_POITER);
}`

Thank you very much!

**Comment by phlptp** [comment]
This has been added and is available in Develop and will be available in the 2.6.0 release upcoming in a few days.

**Comment by phlptp** [comment]
2.6.0 has been merged to master and tagged and should include this function in the C++98 wrapper

**Comment by xcosmos6** [comment]
Thank you very much!

**Comment by xcosmos6** [comment]
Hi @phlptp , 
Is it possible to get current time in the cpp98 wrapper without this getCurrentTime function? I am thinking maybe I can stay with the v2.5.2 and make my code work. So I will downgrade it from v2.6. #1587 
Thank you very much!

**Comment by phlptp** [comment]
the C api is fully accessible when using the C++98 API.  

```
auto time=helicsFederateGetCurrentTime(Fed.baseObject(), NULL);
```

**Comment by xcosmos6** [comment]
Great! it worked. Now I see why this `helicsFederateGetCurrentTime` function didn't work for me before as I didn't use `.baseObject()`. I need to polish up my c++. Thank you very much!!!
