### ISSUE TITLE
`helicsFederateGetOption` doesn't work for all enumerations

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#1549]
**Describe the bug**

`helicsFederateGetOption` doesn't work for the following enumerations:

```
HELICS_FEDERATE_FLAG_ROLLBACK: 12
HELICS_FEDERATE_FLAG_FORWARD_COMPUTE: 14
HELICS_FEDERATE_FLAG_SINGLE_THREAD_FEDERATE: 27
HELICS_FEDERATE_FLAG_DELAY_INIT_ENTRY: 45
HELICS_FEDERATE_FLAG_ENABLE_INIT_ENTRY: 47
```

**What is the expected behavior?**

After creating a federate, I would like to get the values of these options and display to the user.

**Environment (please complete the following information):**

- Operating System: [ Mac ]
- Language Extension: [ Python ]
- Official release on github
- HELICS version: '2.5.2 (2020-06-14)'

**Comment by phlptp** [comment]
These are unused
**
HELICS_FEDERATE_FLAG_ROLLBACK: 12
HELICS_FEDERATE_FLAG_FORWARD_COMPUTE: 14

HELICS_FEDERATE_FLAG_SINGLE_THREAD_FEDERATE: 27

**

will have to think about how to get these since they are in the core vs the typical storage for the others

HELICS_FEDERATE_FLAG_DELAY_INIT_ENTRY: 45
HELICS_FEDERATE_FLAG_ENABLE_INIT_ENTRY: 47

**Comment by kdheepak** [comment]
Okay thanks, I've commented these out for now:

```
HELICS_FEDERATE_FLAG_ROLLBACK: 12
HELICS_FEDERATE_FLAG_FORWARD_COMPUTE: 14
HELICS_FEDERATE_FLAG_SINGLE_THREAD_FEDERATE: 27
```

**Comment by phlptp** [comment]
@kdheepak 

HELICS_FEDERATE_FLAG_DELAY_INIT_ENTRY: 45
HELICS_FEDERATE_FLAG_ENABLE_INIT_ENTRY: 47

these flags are not applicable to federates, they are intended for cores to delay init entry even if all federates are ready.

**Comment by kdheepak** [comment]
Should we rename them to `HELICS_CORE_FLAG_DELAY_INT_ENTRY` and `HELICS_CORE_FLAG_ENABLE_INIT_ENTRY` instead?

**Comment by phlptp** [comment]
That would be my preference.  Those are python specific enumerations as of yet correct?

**Comment by kdheepak** [comment]
I haven't updated anything on the Python side yet. I can update it just in the Python package, or we can update it in both the PyHELICS and HELICS repos.

**Comment by phlptp** [comment]
the symbol `HELICS_FEDERATE_FLAG_*  doesn't exist in the helics repo.  We might add it in helics3 but haven't done so yet.

**Comment by kdheepak** [comment]
Has this always been `HELICS_FLAG_*`? I don't know how these got introduced, my bad. I'll update them in the pyhelics interface.

**Comment by kdheepak** [comment]
Okay, my comments earlier were incorrect, but the code implementation in `pyhelics` is consistent with `helics_enums.h` This is what I'm talking about: 

https://github.com/GMLC-TDC/HELICS/blob/742383907e5ad8af25a97d17a60985976af7c2e1/src/helics/helics_enums.h#L82-L129

The `helics_flag_delay_init_entry` and `helics_flag_enable_init_entry` are part of `helics_federate_flags`.

I think we should have a `helics_federate_flags` and a `helics_core_flags`. Thoughts?

**Comment by phlptp** [comment]
We can discuss this further in helics3,  What about flags that are applicable to both?

**Comment by kdheepak** [comment]
Can we just repeat the flags in both enums? That would be the most straightforward at the expense of a small amount of code duplication.

**Comment by phlptp** [comment]
Are you suggesting just making an enumeration with two elements?  for the enable and delay init entry

**Comment by kdheepak** [comment]
I'm suggesting having a new enumeration for all Core flags, and making the current enumeration only for all the Federate flags.

**Comment by phlptp** [comment]
There are a lot of flags that are for both?

**Comment by kdheepak** [comment]
I would be okay with repeating them explicitly.
