### ISSUE TITLE
`helicsFederateRegisterInterfaces` should throw an error if the publications and inputs are already registered

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#1552]
**Describe the bug**

Currently, if a user calls `helicsCreateValueFederateFromConfig` and then calls `helicsFederateRegisterInterfaces` on the same json file, HELICS does not error.

**What is the expected behavior?**

It should error and present the user with a clear error message.

**To Reproduce**

See https://github.com/GMLC-TDC/HELICS/issues/1493

**Environment (please complete the following information):**

- Operating System: [all]
- Language Extension: [all]
- Latest release from github
- HELICS version: '2.6.0 (2020-08-20)'

**Comment by phlptp** [comment]
I am not sure they should show an error.  The intention was to allow flag modification of previously created interfaces to add targets, or flag controls.  So it shouldn't be an error to have existing interfaces be present in a json file.
