### ISSUE TITLE
Rename `helicsFederateGetCoreObject` to `helicsFederateGetCore` for consistency 

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#1555]
When `HelicsMessageObject` is renamed to `HelicsMessage` in v3, `HelicsCoreObject` is the last type that has the `Object` in the name.

1) Rename `HelicsCoreObject` to `HelicsCore`
2) Rename `helicsFederateGetCoreObject` to `helicsFederateGetCore`

**Comment by phlptp** [comment]
This was done in HELICS 3.0.0-alpha.1
