### ISSUE TITLE
CMake Error at CMakeLists.txt:104

### ISSUE THREAD

**Issue by meghmesh** [GMLC-TDC/HELICS#1556]
I got this error while building on Ubuntu 20.04 (virtual machine). 

CMake Error at CMakeLists.txt:104 (get_filename_component):
  get_filename_component called with incorrect number of arguments

############ Terminal Output ##########################################################

 cmake -DBUILD_PYTHON_INTERFACE=ON -DBUILD_JAVA_INTERFACE=ON -DBUILD_SHARED_LIBS=ON       -DJAVA_AWT_INCLUDE_PATH=NotNeeded -DHELICS_DISABLE_BOOST=ON       -DCMAKE_INSTALL_PREFIX=$TESP_INSTALL -DCMAKE_BUILD_TYPE=Release ..

-- SYSTEM INFO -> Unix Makefiles  Linux-5.4.0-42-generic:GNU-9.3.0
CMake Error at CMakeLists.txt:104 (get_filename_component):
  get_filename_component called with incorrect number of arguments

-- setting up for GNU on Linux-5.4.0-42-generic
-- setting helics C++ standard build option to "-std=c++14"
-- Found ZeroMQ library: /usr/lib/x86_64-linux-gnu/libzmq.so
-- Found ZeroMQ headers: /usr/include
-- Version: 7.0.2
-- Build type: Release
-- CXX_STANDARD: 14
-- Required features: cxx_variadic_templates
-- JsonCpp Version: 1.9.2
-- Build spdlog: 1.7.0
-- Build type: Release
-- Boost dir= /usr/include
-- Building without swig
-- Building without swig
-- Git hooks disabled
-- Configuring incomplete, errors occurred!
See also "/home/meghana/src/HELICS-src/build/CMakeFiles/CMakeOutput.log".
See also "/home/meghana/src/HELICS-src/build/CMakeFiles/CMakeError.log".

**Comment by phlptp** [comment]
What is in $TESP_INSTALL?  If that is empty that could be the source of the error.  
That line is checking something with the CMAKE_INSTALL_PREFIX

**Comment by nightlark** [comment]
It looks like this error does happen when the `CMAKE_INSTALL_PREFIX` is empty.

On the off-chance you actually wanted to use the root directory as the install prefix, setting it to `/` works.

**Comment by phlptp** [comment]
@meghmesh  I think we are going to close this issue.  The PR added a more explicit warning about what was going on and won't generate an error any more if you wanted the install prefix to be empty.    Thanks for pointing this out.
