### ISSUE TITLE
Errors in filter definitions not producing error messages

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#1601]
Parsing of the `reroute` filter parameters does not produce error messages.

The sample below was tested with HELICS 2.6.0 and 2.4.2 using pyhelics on macOS 10.15.6 and in both cases no error messages were produced. Note the filter type is `rereoute3` which is not a valid option.

```
 "filters": [
    {
      "name": "fromEV1.soc",
      "sourcetargets": "EV_federate/EV1.soc",
      "operation": "reroute3",
      "properties": [
        {
          "name": "newdestination",
          "value": "filter/main"
        }
      ],
      "info": "EV_federate"
    },
    {
```

**Comment by phlptp** [comment]
Fixed in #1607
