### ISSUE TITLE
Broker query shows "init_requested" after entering execution mode

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#1604]
I'm running queries on the broker during init and during execution and they both return the same "state" string for all federates. This is true even though only one of the federates has entered init mode.

I'm running PyHELICS v2.6.0 on macOS 10.15.6

Query:
```
    h.helicsQuerySetQueryString(query, "current_state")
    current_state = h.helicsQueryExecute(query, fed)
    logger.debug(f'Init current state: {current_state}')
```
Output when run from after entering init:
```
Init current state: {
   "brokers" : [],
   "cores" : 
   [
      {
         "id" : 1879048192,
         "name" : "89246-5VqvL-VufCM-flQYa-48UM1",
         "state" : "init_requested"
      },
      {
         "id" : 1879048193,
         "name" : "89244-spn81-EmVW1-2jW8W-jED23",
         "state" : "init_requested"
      },
      {
         "id" : 1879048194,
         "name" : "89245-bBn2Y-iqSvf-Ap4eV-2djVj",
         "state" : "init_requested"
      }
   ],
  ...
```

Output after entering execution:
```
Entered HELICS execution mode
Execution current state: {
   "brokers" : [],
   "cores" : 
   [
      {
         "id" : 1879048192,
         "name" : "89246-5VqvL-VufCM-flQYa-48UM1",
         "state" : "init_requested"
      },
      {
         "id" : 1879048193,
         "name" : "89244-spn81-EmVW1-2jW8W-jED23",
         "state" : "init_requested"
      },
      {
         "id" : 1879048194,
         "name" : "89245-bBn2Y-iqSvf-Ap4eV-2djVj",
         "state" : "init_requested"
      }
   ],
  ...
```

**Comment by phlptp** [comment]
The current state shows the information available in the broker.  The broker really only gets a few indications from federates.  created, init_requested, final,  Everything else is local so this is as expected.    Additional information is much more time consuming to collect.    There might be another query that does that already though.

**Comment by trevorhardy** [comment]
Oh, OK. I propose we change "init_requested" to "running" or something similarly generic so that others don't get confused.

Knowing whether the other federates are in "init" or "execution" would be useful (for things like dynamic configuration) but we can treat that as a separate issue if you want.

**Comment by phlptp** [comment]
I was looking at that,  I am creating a "global_state" query which is much more intensive that will get that information since it needs to query the federates themselves for that information since it isn't available globally.    The current_state query only gets local information

**Comment by phlptp** [comment]
The transition from init to executing is a local function and not globally available.

**Comment by phlptp** [comment]
This has been resolved by the addition of a "global_state" query
