### ISSUE TITLE
When importing helics in Python we get a git error message: `fatal: bad revision 'HEAD'`

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#1633]
I think that there's a call to `git` in `_version.py` in the `helics` package that causes this to be printed on the user's end on Windows. The user installed helics using `conda install -c gmlc-tdc helics`.

![Screen Shot 2020-10-05 at 3 17 43 PM](https://user-images.githubusercontent.com/1813121/95133088-fb825200-071d-11eb-9857-6a9085a463f1.png)

This does not occur on Mac or Linux. 

This `_version.py` setup is not used in the new pyhelics interface.

**Comment by nightlark** [comment]
That's interesting. It looks like a bug with versioneer -- is the package install directory that conda uses a git repository?

We should see if we can get a version with the bug fixed or implement our own version of _version.py for the new pyhelics interface, to make version updates easier and support continuous deployment of test versions to test pypi.

**Comment by phlptp** [comment]
Has this been resolved @kdheepak @nightlark ?

**Comment by nightlark** [comment]
Yes, the last version of the swig Python interface released on PyPI fixed usage of the versioneer command class so that it works.
