### ISSUE TITLE
Change `helicsEndpointSendTo` and `helicsEndpointSendToAt` argument order

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#1653]
Currently in the v3 release, we have the following function signature:

```
helicsEndpointSendTo(endpoint, destination, data, inputDataLength, err)
helicsEndpointSendToAt(endpoint, destination, time, data, inputDataLength, err)
```

I think we should make it this instead:

```
helicsEndpointSendTo(endpoint, data, inputDataLength, destination, err)
helicsEndpointSendToAt(endpoint, data, inputDataLength, destination, time, err)
```

1) I think it reads better. We "send the data of some length to the destination at a time".
2) For a pythonic interface I'd like to make a single "send" function, and having the "optional" argument for time at the end making sense.

**Comment by kdheepak** [comment]
This is an example implementation of the single `send_message` function:

```python
class HelicsEndpoint:

    ...

    def send_message(self, data: Union[str,HelicsMessage], destination: str = None, time = None):
        if type(data) == HelicsMessage:
            helicsEndpointSendMessage(self, data)
        elif time is None:
            helicsEndpointSendTo(self, dest, data)
        else:
            helicsEndpointSendToAt(self, dest, time, data)

```

**Comment by phlptp** [comment]
@nightlark  @bmkelley  @trevorhardy  what do you think of this?

**Comment by trevorhardy** [comment]
No problems on my end. Consistency in the two signatures is most important and to the extent we can make life easier for the C-based bindings, that's always good.

**Comment by bmkelley** [comment]
> No problems on my end. Consistency in the two signatures is most important and to the extent we can make life easier for the C-based bindings, that's always good.

+1

**Comment by nightlark** [comment]
👍 

Changing the argument order makes it feel like the function signature is easier to remember later. I think there was also a `SendAt` method that should also be changed to match.
