### ISSUE TITLE
`flagStringsTranslations` doesn't have `observer`, `uninterruptible`, `interruptible`

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#1664]
https://github.com/GMLC-TDC/HELICS/blob/2ef452943cc79d5572c9a860b05e03d96af0d6f6/src/helics/application_api/FederateInfo.cpp#L70-L107

Also it has some of `helics_handle_option` in there. Is there a reason for that?

**Comment by phlptp** [comment]
handle options for a federate become the default for all new interfaces
