### ISSUE TITLE
helics exceptions are not being printed in python

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#1671]
Here is the current HELICS error message in Python using swig, v2.6.1

![Screen Shot 2020-10-30 at 2 46 43 PM](https://user-images.githubusercontent.com/1813121/97755425-c2d85d00-1abe-11eb-810e-2ef4ceca27cb.png)

Here is the same HELICS error message in Python using the new pyhelics interface, v2.6.1.post0.dev0

![Screen Shot 2020-10-30 at 2 45 33 PM](https://user-images.githubusercontent.com/1813121/97755378-a9cfac00-1abe-11eb-952c-070c7118d054.png)

**Comment by kdheepak** [comment]
This will be resolved when the new python interface is released.

**Comment by phlptp** [comment]
Can this be closed? @kdheepak

**Comment by kdheepak** [comment]
Yes!
