### ISSUE TITLE
Unable to run co-sim on custom broker port

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#1716]
**Describe the bug**
When specifying the coreInitString for a federate and using it to set the address and port of the broker, log files reveal that connections are being attempted at one port number than what was specified.

**To Reproduce**
Federate config:
```json
  "name": "Charger",
  "loglevel": 1,
  "coreType": "zmq",
  "coreInitString": "--broker=tcp://10.0.1.17:20200",
  "period": 60,
```

helics_cli launch script:
```json
{
  "federates": [    
    {
      "directory": ".",
      "exec": "helics_broker -f 3 --loglevel=1 --port=20200",
      "host": "localhost",
      "name": "broker"
    },

```

Output in Charger.log
```
[2020-11-11 10:49:03.922] [console] [warning] commWarning||60252-sKzw5-g1Hrz-qzZyE-kjzQb (0)::zmq broker connection timed out, trying again (2)
[2020-11-11 10:49:03.922] [console] [warning] commWarning||60252-sKzw5-g1Hrz-qzZyE-kjzQb (0)::sending message to tcp://10.0.1.17:20201
```

**Environment (please complete the following information):**

- Operating System: Mac OS 10.14.6
- Language Extension: Python
- Compiled from source, using pyhelics
- HELICS version: 3.0.0-alpha.2

```
$ helics run --path=federation_1_runner.json
```

**Additional context and information**
The full example can be found here: https://github.com/GMLC-TDC/HELICS-Examples/tree/master/user_guide_examples/advanced/advanced_brokers/simulataneous

**Comment by phlptp** [comment]
It is possible there is other issues here, but the port on the message is the specified port +1 which since the ZMQ comms uses two ports is to be expected.   So it is using the specified port

**Comment by trevorhardy** [comment]
OK, the co-sim doesn't run and I'm trying to figure out why but it's clear it's not the port number. I'll change the issue title and plan on working on this with @eberleim on Monday.

**Comment by trevorhardy** [comment]
Resolved and demonstrated in the [advanced User Guide examples](https://github.com/GMLC-TDC/HELICS-Examples/tree/master/user_guide_examples/advanced/advanced_brokers)
