### ISSUE TITLE
HELICS native filters prevent message receipt?

### ISSUE THREAD

**Issue by allisonmcampbell** [GMLC-TDC/HELICS#1733]
Using v3 alpha2, I have two message federates. When I exclude the filter (delaying message from only 1 federate), the cosim works. 

Abbreviated versions of their config files:

```
{
  "name": "Battery",
  "loglevel": 7,
  "coreType": "zmq",
  "period": 1.0,
  "offset": 10.0,
  "uninterruptible": false,
  "terminate_on_error": true,
  "endpoints":[
    {
      "key":"Battery/EV1_current",
      "destination":"Charger/EV1_voltage",
      "global": true
    }

{
  "name": "Charger",
  "loglevel": 7,
  "coreType": "zmq",
  "period": 1,
  "uninterruptible": false,
  "terminate_on_error": true,
  "endpoints":[
    {
      "key":"Charger/EV1_voltage",
      "destination":"Battery/EV1_current",
      "global": true
    }
  ]
  "filters":
  [
    {
      "name":"Charger_filter1",
      "sourcetarget":"Charger/EV1_voltage",
      "mode":"source",
      "operation":"delay",
      "properties":
      {
        "name":"delay",
        "value":5
      }
    }
  ]
}
```

Time is updated in the Battery federate as:

```
    update_interval = 60*int(h.helicsFederateGetTimeProperty(
                                fed,
                                h.helics_property_time_period))
    update_offset = int(h.helicsFederateGetTimeProperty(
                                fed,
                                h.helics_property_time_offset))

...
requested_time = (grantedtime+update_interval+update_offset)
```

And in the Charger federate as:

```
    initial_time = 60
    logger.debug(f'Requesting initial time {initial_time}')
    grantedtime = h.helicsFederateRequestTime(fed, initial_time )

...
    requested_time = (grantedtime + update_interval)
```

When I include the filter (as above), the federate which has a source delay (Charger) does not receive messages.

The log files show that the initial message from Charger to Battery is delayed by 5 seconds and received:

```
Requesting time 70
DEBUG:__main__:Requesting time 70
Granted time 65.0
DEBUG:__main__:Granted time 65.0
Battery 1 time 65.0
DEBUG:__main__:Battery 1 time 65.0
Received message voltage 240.00 at endpoint Battery/EV1_current from Charger/EV1_voltage at time 65.0
DEBUG:__main__:Received message voltage 240.00 at endpoint Battery/EV1_current from Charger/EV1_voltage at time 65.0
```

And a message is sent from the Battery federate to the Charger federate at time = 65:

```
Sent message 10.16 from endpoint Battery/EV1_current to endpoint Charger/EV1_voltage at time 65.0
```

However, this message is not received by Charger:

```
Requesting time 120.0
DEBUG:__main__:Requesting time 120.0
Granted time 120.0
DEBUG:__main__:Granted time 120.0
EV 1 time 120.0
DEBUG:__main__:EV 1 time 120.0
        No messages at endpoint Charger/EV1_voltage recieved at time 120.0
```

The expectation is that there would be a message waiting for Charger beginning at time = 65, however the Charger does not have a message.

- Operating System: [Mac]
- Language Extension: [Python]

```
$ helics_app --version
3.0.0-alpha.2-helics3-gd501f17 (2020-11-10)
```

**Comment by trevorhardy** [comment]
Tested on HELICS v3.1 and PyHELICS v3.1.0 and this is issue is manifesting slightly differently. After [testing the User Guide example that deals with native filters ](https://github.com/GMLC-TDC/HELICS-Examples/tree/main/user_guide_examples/fundamental/fundamental_message_comm/filter_native), including or excluding the source delay filter for the Charger federate does not affect when the messages arrive. In this case of the example, a 900s source delay filter is created but a message from the Battery federate arrives at t=120s.

**Comment by trevorhardy** [comment]
On HELICS v3.2.0 and PyHELICS v3.2.0post1 [testing the User Guide example that deals with native filters ](https://github.com/GMLC-TDC/HELICS-Examples/tree/main/user_guide_examples/fundamental/fundamental_message_comm/filter_native) this issue appears resolved.
