### ISSUE TITLE
double publications don't propagate to other federates when iteration if needed in HELICS v2.5.2 onwards

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#1741]
**Describe the bug**

We have double publications and have set up a simple example in Python to do co-iteration. The values subscribed while iteration is occurring update as expected based on the values that are being published  when using HELICS v2.5.0 or HELICS v2.5.1.

However, when using v2.5.2, v2.6.0, v2.6.1 the values don't update anymore and only the last published value is being retrieved on the subscription in each iteration step.

**Environment (please complete the following information):**

- Operating System: [Windows]
- Language Extension: [Python]
- Bug confirmed to exist in PyHELICS 2.6.0.post4 with environment variable pointing to 2.5.2, 2.6.1. It does not exist when the environment variable is updated to point to 2.5.1.
- HELICS version: 2.5.1 / 2.5.2

cc: @AadilLatif @nadiavp

**Comment by phlptp** [comment]
Is this an issue any more? @kdheepak
