### ISSUE TITLE
Standardize all HELICS queries to return JSONs?

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#1746]
**Describe the bug**
Running a global query fails.

**To Reproduce**
Battery.py:
```
    core = h.helicsFederateGetCoreObject(fed)
    h.helicsCoreSetGlobal(core, "global_variable_test", "global test value")
```

Charger.py:
```
    query = h.helicsCreateQuery("global", "global_variable_test")
    result = h.helicsQueryExecute(query, fed)
    logger.debug(f'global_variable_test = {result}')
```
Error message on the query:
```
  File "Charger.py", line 224, in <module>
    result = h.helicsQueryExecute(query, fed)
  File "/Users/hard312/source/HELICS/pyhelics/helics/capi.py", line 4415, in helicsQueryExecute
    return json.loads(ffi.string(result).decode())
  File "/Users/hard312/opt/anaconda3/envs/HELICS_UG/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Users/hard312/opt/anaconda3/envs/HELICS_UG/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/hard312/opt/anaconda3/envs/HELICS_UG/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

- Operating System: Mac 10.14.6
- Language Extension: Python (PyHELICS)
- HELICS version: v3alpha2

@kdheepak has already stated on Gitter that this bug is likely caused by PyHELICS expecting a JSON to be returned but HELICS not doing so.

**Comment by kdheepak** [comment]
@trevorhardy you can use the latest `master` version in `pyhelics` to not get this error (although it just returns the string if it is not able to decode it as a json, which will change when HELICS queries always return json).

**Comment by trevorhardy** [comment]
@kdheepak, I've pulled in the new version and from the source folder did a `pip install -e .` and I'm not seeing a new version number when I do `helics --version`; is that expected?

**Comment by trevorhardy** [comment]
@kdheepak, apparently it is because the version that is installed now is able to catch the global query; thanks!

I'll leave it up to you and @phlptp to decide if we want this to be a permanent fix or if we also want to update HELICS so that it always returns a JSON.

**Comment by phlptp** [comment]
I am going to close this as I think it is done in HELICS 3.  The only query that purposely doesn't return valid JSON is "global_value"
