### ISSUE TITLE
` duplicate broker detected ` occurs when there are federates with the same name 

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#1747]
**Describe the bug**

Incorrect occur is presented to the user. Duplicate federate name should be thrown as an error to the user.

**Environment (please complete the following information):**

- Operating System: [all | Windows | Mac | Linux]
- Language Extension: [all | Python | Julia ]
- HELICS version: 2.6.1

**Comment by phlptp** [comment]
I have been looking through the code for this error, and all the places I look indicate correct error strings.  
Can be more specific on where you were seeing this?

**Comment by kdheepak** [comment]
If `core_name` is not defined in the json and a user uses `helicsCreateValueFederateFromConfig`, even if `name` is different in the json file, the error that is reported is `duplicate broker detected` and it is not clear from the error what is going on. See files in this commit as an example:

https://github.com/GMLC-TDC/HELICS-Examples/commit/ddc9a6b83c0ea32b3399de7a08ac8fda0d7d1a52
