### ISSUE TITLE
Improve documentation for complex networking environments

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#1827]
Complex networking environments (including but not limited to heterogenous HPC and cloud services) can present particular challenges for HELICS. Though it is not possible for the HELICS documentation to provide sufficient education on networking practices/management to help HELICS users, it should be possible to help HELICS users understand when they might be treading into a place where using some of the network-centric HELICS configuration options may be required. The documentation needs to be updated to provide such guidance.

**Comment by nightlark** [comment]
#2316 adds some more documentation on complex networking environments, which seems to be related to this issue (though maybe not everything needed to address the issue?).
