### ISSUE TITLE
best way to handle source-only controller in a real-time environment

### ISSUE THREAD

**Issue by mzy2240** [GMLC-TDC/HELICS#1914]
What's the best practice to model an open-loop source-only real-time controller federate? especially the timing part.

Let's say we have a real-time simulator A that periodically sends signal to controller B, this could be quickly done using HELICS. And there is another controller C, which does not request any data from A, but will sometimes send signal to simulator A (based on user input, so unpredictable). In this situation, do I have to send a dummy signal from simulator A to controller C just in order to synchronize the granted time(no other helics connection for controller C)? If this is not the only way, what other options/best practices do we have to make simulator A responsive to controller C (with minimal latency)?

Thank you in advance!

**Comment by phlptp** [comment]
If simulator A can receive signals from C,  HELICS will not let A advance past the granted Time of Federate C.    

So to generate unpredictable events in C to A.  You can set federate C to real time mode, meaning it syncs to wall clock time.  Then your program in C just loops on some small period and checks for input.   This will force all other federates to operate in real time as well.  Or you can add an extra dependency from A to C.  This would allow it to advance faster than real time if desired.

**Comment by mzy2240** [comment]
Thanks! I actually tried the second way - creating additional dependency from A to C and it works great. I will try the real time mode in other applications.
