### ISSUE TITLE
Replace Docker Hub Autobuilds

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/HELICS#1949]
Docker Hub Autobuilds is going away for the free tier - https://www.docker.com/blog/changes-to-docker-hub-autobuilds/

I think we have some builds running there, so we'll either need to try to join the Open Source program they have, or build the images elsewhere and push them to Docker Hub.

**Comment by phlptp** [comment]
I would guess the most logical option would be github actions like we do for the buildenv repo.
