### ISSUE TITLE
`wait_for_current_time_update` flag causes co-sim to hang

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#1958]
**Describe the bug**
Adding a `wait_for_current_time_update` flag to either federate in the [User Guide endpoint example](https://github.com/GMLC-TDC/HELICS-Examples/tree/master/user_guide_examples/fundamental/fundamental_message_comm/endpoints) causes the co-simulation to hang.

**What is the expected behavior?**
Adding this flag to a single federate in the federation should not cause the federation to hang.

**To Reproduce**
Run the example adding the following line to either `BatteryConfig.json` or `ChargerConfig.json`: `"wait_for_current_time_update": true,`

**Environment (please complete the following information):**
- Operating System: Mac
- Language Extension: python (pyhelics 2.7..1)
- HELICS version: v3 beta, built locally from source

**Additional context and information**
The [User Guide's fundamental default example](https://github.com/GMLC-TDC/HELICS-Examples/tree/master/user_guide_examples/fundamental/fundamental_default) also utilizes this flag but does not hang. That example uses pub/sub whereas the one that hangs only uses endpoint.

**Comment by phlptp** [comment]
at which point is it hanging?

**Comment by trevorhardy** [comment]
Both federates get granted at least one time and depending on which one has the flag, I believe one of them gets granted a second time.

**Comment by phlptp** [comment]
@trevorhardy  can you check if this is fixed or not?

**Comment by trevorhardy** [comment]
This example is working in v3b2. Closing for now.
