### ISSUE TITLE
missing `#include <thread>` in AsioContextManager.cpp and helicsExport.cpp

### ISSUE THREAD

**Issue by beroset** [GMLC-TDC/HELICS#1960]
Compiling under Fedora 34 using gcc 11.1.1, the compiler complains that `std::this_thread::sleep_for` is not part of `std::thread`.  The cause is that the code is missing `#include <thread>`.  This probably compiles with other versions of gcc or clang because another include, such as `<mutex>` happens to already include `<thread>`, but of course that's not portable.

**Comment by phlptp** [comment]
Thanks, We will make that change.  I don't think we had tested with gcc 11 yet.  So we should probably get a CI build going with gcc 11 as well.
