### ISSUE TITLE
`flag not recognized` when calling `helicsFederateGetFlagOption`

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#2084]
For the following flags, I'm getting `flag not recognized` error message:

```
[-203] flag not recognized HelicsFederateFlag.LOCAL_PROFILING_CAPTURE
[-203] flag not recognized HelicsFederateFlag.STRICT_CONFIG_CHECKING
[-203] flag not recognized HelicsFederateFlag.USE_JSON_SERIALIZATION
[-203] flag not recognized HelicsFlag.PROFILING
[-203] flag not recognized HelicsFlag.PROFILING_MARKER
```

**Comment by phlptp** [comment]
what is the code generating that error?

**Comment by kdheepak** [comment]
I believe it was `helicsFederateGetFlagOption`.

**Comment by kdheepak** [comment]
https://github.com/GMLC-TDC/pyhelics/blob/b87c558e50b2309e6b29f0fd5497699c8418c013/helics/capi.py#L1620-L1631

**Comment by phlptp** [comment]
are you doing this on HELICS 2 or 3?

**Comment by phlptp** [comment]
this should be fixed in develop and helics2 now

**Comment by phlptp** [comment]
@kdheepak  can you check on this

**Comment by phlptp** [comment]
@kdheepak  is there any current issues regarding this topic otherwise I am going to close the issue as I believe it has been fixed
