### ISSUE TITLE
Build Universal 2 binaries for macOS releases

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/HELICS#2122]
The macOS release binaries should include native support for arm64.

On an intel mac, I used this command for building Universal 2 binaries:
`cmake .. -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DHELICS_DISABLE_BOOST=ON -DHELICS_ZMQ_SUBPROJECT=ON -DHELICS_ZMQ_FORCE_SUBPROJECT=ON`

For the release build workflows, `HELICS_ZMQ_FORCE_SUBPROJECT` and `HELICS_DISABLE_BOOST` aren't needed.

Adding support for release builds should be mostly adding `-DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"` to the cmake configure step in these two files:
- https://github.com/GMLC-TDC/HELICS/blob/main/.github/actions/release-build/installer-macOS.sh
- https://github.com/GMLC-TDC/HELICS/blob/main/.github/actions/release-build/shared-library-macOS.sh

After that it should be validating on a mac that the artifacts produced by the release workflow are universal binaries.

**Comment by nightlark** [comment]
These scripts are set up to run on GitHub Actions using a macOS VM in the [release-build.yml workflow](https://github.com/GMLC-TDC/HELICS/blob/main/.github/workflows/release-build.yml). An automated check to make sure the resulting fat binary has support for both `x86_64` and `arm64` native code would be a nice to have.

**Comment by parthb83** [comment]
Hi @nightlark! I would like to take up this issue. Please guide me through what I have to do.

**Comment by nightlark** [comment]
Hey @parthb83! I'd start from working off the `develop` branch in your fork (sync'd with the latest changes in this repository).

After making changes to the scripts mentioned in the issue, you can test the changes by going to the Actions tab (https://github.com/parthb83/HELICS/actions) in your repository (enabling workflows if you haven't already), then trigger the `Build release artifacts` on the `develop` branch. I've tried to highlight the key parts in the images below.

<img width="616" alt="trigger-release-workflow-helics" src="https://user-images.githubusercontent.com/3969255/137796202-026b19e0-4cc1-49d3-b7e5-ca0cffb38d7d.PNG">

If you need to permissions for actions, there's the `Actions` section under the `Settings` tab for your fork that you can use to change what Actions are allowed to run. At minimum I think `Allow select actions` with `Allow actions created by GitHub` is required for the release build workflow.

**Comment by parthb83** [comment]
Thank you @nightlark for this guide. I tested the changes specified by you by triggering the build release artifacts on the develop branch. You can see the results of those tests here: https://github.com/parthb83/HELICS/actions/runs/1356257861. You can also review my PR: #2128.
