### ISSUE TITLE
Update Azure Pipelines XCode-oldest job to use macOS 10.15

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/HELICS#2123]
As part of [recently announced image deprecation for Azure Pipelines](https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/), the macOS XCode-oldest job needs updating to use a newer image.

Things that need to get done to update the [XCode-oldest job on Azure Pipelines](https://github.com/GMLC-TDC/HELICS/blob/main/.ci/azure-pipelines.yml#L58) file:
- Change the `vmImage` to run on `macOS-10.15`
- This will also require bumping up the XCode version pointed to by `xcode_path` to the minimum on the macOS-10.15 virtual environment (likely 10.3)

**Comment by parthb83** [comment]
Please review the PR: #2127.
