### ISSUE TITLE
Update Windows versions used for CI builds for upcoming vm image deprecation

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/HELICS#2124]
As part of [recently announced image deprecation for Azure Pipelines](https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/), the Windows jobs need updating to use a newer image by March 2022.

Update the [Windows jobs on Azure Pipelines](https://github.com/GMLC-TDC/HELICS/blob/main/.ci/azure-pipelines.yml#L91)
- Change the `VS2017-32bit` and `VS2017-64bit` jobs to run on VS2019
- Change the `VS2019-64bit` job to run on VS2022
- Update the [build requirements for Windows on the installation docs page](https://docs.helics.org/en/latest/user-guide/installation/windows.html)

Update the [Windows release build jobs on GitHub Actions](https://github.com/GMLC-TDC/HELICS/blob/main/.github/workflows/release-build.yml)
- Change builds using `windows-2016` to `windows-2019`
- Change builds using `windows-2019` to `windows-2022`

**Comment by nightlark** [comment]
[Blog post announcing the March 15, 2022 removal of windows-2016 images on GitHub Actions](https://github.blog/changelog/2021-10-19-github-actions-the-windows-2016-runner-image-will-be-removed-from-github-hosted-runners-on-march-15-2022/)

They have brownouts scheduled for:
- December 1, 2021 4:00pm UTC – 10:00pm UTC
- February 7, 2022 4:00pm UTC – 10:00pm UTC

**Comment by parthb83** [comment]
Hey @nightlark! I would like to work on this issue. Please guide me on the process of how to solve this issue.

**Comment by nightlark** [comment]
Alright, so I think for this change we want to take a more gradual approach, since among the commercial simulators there seem to be a fair number that require 32-bit builds

For GitHub Actions the [docs on the VMs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) show the windows-2022 image as `[beta]` and the first full VS 2022 is technically not coming out until November 8. Instead of changing the existing builds, let's add msvc2022 to matrix for the [build-windows-msvc release build job](https://github.com/GMLC-TDC/HELICS/blob/main/.github/workflows/release-build.yml#L55).
- Add matrix entry for msvc2022 release builds that runs using the windows-2022 image
- Change the `windows-latest` images used by several release build jobs to `windows-2019` to make sure they don't suddenly change when `windows-latest` gets updated

For Azure Pipelines, I'm thinking a `Daily Windows` job for `windows-2022` added to [.ci/azure-pipelines-daily.yml](https://github.com/GMLC-TDC/HELICS/blob/main/.ci/azure-pipelines-daily.yml) that's based on the [windows job in .ci/azure-pipelines.yml](https://github.com/GMLC-TDC/HELICS/blob/main/.ci/azure-pipelines.yml#L91) would be a good way to become aware of any VS 2022 issues that need to be fixed.

**Comment by parthb83** [comment]
Sure! I'll give it a try.😀

**Comment by phlptp** [comment]
@nightlark  can this be closed?

**Comment by nightlark** [comment]
@phlptp there's a few changes to make after the next HELICS 2/3 release(s):
- remove VS2017 from GitHub release build workflow
- remove VS2017 from Azure Pipelines CI builds
