### ISSUE TITLE
Add user guide support page link to GitHub Discussions

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/HELICS#2125]
The entry on the [user guide support page to the forums](https://github.com/GMLC-TDC/HELICS/blob/develop/docs/user-guide/support.md?plain=1#L11) should be updated to link to https://github.com/GMLC-TDC/HELICS/discussions, and the text should be updated to reflect that it is now available.

**Comment by slashgk** [comment]
Please assign this to me and also add the hacktoberfest label.
