### ISSUE TITLE
Generate diagrams in docs from textual descriptions/markup

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/HELICS#2131]
Currently most of the diagrams in the docs are in a format that makes updates tricky (raster images).

An example of one of these is the flowchart for installing HELICS: https://docs.helics.org/en/latest/user-guide/installation/index.html

I tried converting it to a diagram generated using `Mermaid` which is a markdownish syntax for generating diagrams. Here are the initial results (image links to the "live" editor, and the image is generated on the fly so it might take a moment to appear):
[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBKERvIHlvdSB3YW50IHRvIGluc3RhbGwgYSA8YnIvPiBzdGFuZGFyZCBIRUxJQ1MgdmVyc2lvbj8pIC0tPnxZZXN8IEIoV2hhdCBsYW5ndWFnZSBhcmUgPGJyLz4geW91IHVzaW5nPylcbiAgICBBIC0tPnxOb3wgQ1tCdWlsZCBmcm9tIHNvdXJjZSBmb3IgdGhlIDxici8-IHBhcnRpY3VsYXIgYnJhbmNoIG9yIDxici8-IGNvbmZpZ3VyYXRpb24gdGhhdCB5b3UgbmVlZC5dXG4gICAgQiAtLT4gRChQeXRob24pXG4gICAgQiAtLT4gRShDL0MrKylcbiAgICBCIC0tPiBGKEp1bGlhKVxuICAgIEIgLS0-IEcoT2N0YXZlL0phdmEvIDxici8-IE1BVExBQi9DIylcbiAgICBCIC0tPiBIKE5pbSlcbiAgICBEIC0tPiBJW1VzZSBwaXA6IDxici8-IHBpcCBpbnN0YWxsIGhlbGljc11cbiAgICBFIC0tPiBKKEFyZSB5b3UgdXNpbmcgYSA8YnIvPiBXaW5kb3dzIE9TPylcbiAgICBGIC0tPiBLW1VzZSBwa2c6IDxici8-IHBrZz4gYWRkIEhFTElDU11cbiAgICBHIC0tPiBMW0Rvd25sb2FkIHRoZSBwcmUtY29tcGlsZWQgPGJyLz4gbGlicmFyaWVzIGFuZCBhZGQgdGhlbSA8YnIvPiB0byB5b3VyIHN5c3RlbSBwYXRoLCB0aGVuIDxici8-IGJ1aWxkIHRoZSBleHRlbnNpb24gd2l0aCA8YnIvPiBTV0lHXVxuICAgIEggLS0-IE1bVXNlIG5pbWJsZTogPGJyLz4gbmltYmxlIGluc3RhbGwgPGJyLz4gaHR0cHM6Ly9naXRodWIuY29tL0dNTEMtIDxici8-IFREQy9oZWxpY3MubmltI2hlYWRdXG4gICAgSiAtLT58WWVzfCBOW0Rvd25sb2FkIHRoZSBwcmUtIDxici8-IGNvbXBpbGVkIGxpYnJhcmllcyBhbmQgPGJyLz4gYWRkIHRoZW0gdG8geW91ciA8YnIvPiBzeXN0ZW0gcGF0aF1cbiAgICBKIC0tPnxOb3wgTyhXaWxsIHlvdSBiZSB1c2luZyBIRUxJQ1MgPGJyLz4gb24gYW4gSFBDIFN5c3RlbSBhbmQvb3IgPGJyLz4gd291bGQgeW91IGxpa2UgdG8gdXNlIHRoZSA8YnIvPiBzcGFjayBwYWNrYWdlIGluc3RhbGxlcj8pXG4gICAgTyAtLT58Tm98IE5cbiAgICBPIC0tPnxZZXN8IFBbVXNlIHNwYWNrOiA8YnIvPiBzcGFjayBpbnN0YWxsIGhlbGljc10iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOnRydWUsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjp0cnVlfQ)](https://mermaid.live/edit/#eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBKERvIHlvdSB3YW50IHRvIGluc3RhbGwgYSA8YnIvPiBzdGFuZGFyZCBIRUxJQ1MgdmVyc2lvbj8pIC0tPnxZZXN8IEIoV2hhdCBsYW5ndWFnZSBhcmUgPGJyLz4geW91IHVzaW5nPylcbiAgICBBIC0tPnxOb3wgQ1tCdWlsZCBmcm9tIHNvdXJjZSBmb3IgdGhlIDxici8-IHBhcnRpY3VsYXIgYnJhbmNoIG9yIDxici8-IGNvbmZpZ3VyYXRpb24gdGhhdCB5b3UgbmVlZC5dXG4gICAgQiAtLT4gRChQeXRob24pXG4gICAgQiAtLT4gRShDL0MrKylcbiAgICBCIC0tPiBGKEp1bGlhKVxuICAgIEIgLS0-IEcoT2N0YXZlL0phdmEvIDxici8-IE1BVExBQi9DIylcbiAgICBCIC0tPiBIKE5pbSlcbiAgICBEIC0tPiBJW1VzZSBwaXA6IDxici8-IHBpcCBpbnN0YWxsIGhlbGljc11cbiAgICBFIC0tPiBKKEFyZSB5b3UgdXNpbmcgYSA8YnIvPiBXaW5kb3dzIE9TPylcbiAgICBGIC0tPiBLW1VzZSBwa2c6IDxici8-IHBrZz4gYWRkIEhFTElDU11cbiAgICBHIC0tPiBMW0Rvd25sb2FkIHRoZSBwcmUtY29tcGlsZWQgPGJyLz4gbGlicmFyaWVzIGFuZCBhZGQgdGhlbSA8YnIvPiB0byB5b3VyIHN5c3RlbSBwYXRoLCB0aGVuIDxici8-IGJ1aWxkIHRoZSBleHRlbnNpb24gd2l0aCA8YnIvPiBTV0lHXVxuICAgIEggLS0-IE1bVXNlIG5pbWJsZTogPGJyLz4gbmltYmxlIGluc3RhbGwgPGJyLz4gaHR0cHM6Ly9naXRodWIuY29tL0dNTEMtIDxici8-IFREQy9oZWxpY3MubmltI2hlYWRdXG4gICAgSiAtLT58WWVzfCBOW0Rvd25sb2FkIHRoZSBwcmUtIDxici8-IGNvbXBpbGVkIGxpYnJhcmllcyBhbmQgPGJyLz4gYWRkIHRoZW0gdG8geW91ciA8YnIvPiBzeXN0ZW0gcGF0aF1cbiAgICBKIC0tPnxOb3wgTyhXaWxsIHlvdSBiZSB1c2luZyBIRUxJQ1MgPGJyLz4gb24gYW4gSFBDIFN5c3RlbSBhbmQvb3IgPGJyLz4gd291bGQgeW91IGxpa2UgdG8gdXNlIHRoZSA8YnIvPiBzcGFjayBwYWNrYWdlIGluc3RhbGxlcj8pXG4gICAgTyAtLT58Tm98IE5cbiAgICBPIC0tPnxZZXN8IFBbVXNlIHNwYWNrOiA8YnIvPiBzcGFjayBpbnN0YWxsIGhlbGljc10iLCJtZXJtYWlkIjoie1xuICBcInRoZW1lXCI6IFwiZGVmYXVsdFwiXG59IiwidXBkYXRlRWRpdG9yIjp0cnVlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6dHJ1ZX0)

The diagram could either be exported as an svg, or mermaid-js could be included to render the diagram on the fly in browsers (I think either of these could be used to add clickable links in the diagram too).

https://kroki.io/ could be used to automate the conversion to an svg when a PR is made that changes the "source" files for a diagram (it supports markups for generating many different types of diagrams/images).

The converted flowchart source linked above looks like this (styling can be customized):
```
graph TD
    A(Do you want to install a <br/> standard HELICS version?) -->|Yes| B(What language are <br/> you using?)
    A -->|No| C[Build from source for the <br/> particular branch or <br/> configuration that you need.]
    B --> D(Python)
    B --> E(C/C++)
    B --> F(Julia)
    B --> G(Octave/Java/ <br/> MATLAB/C#)
    B --> H(Nim)
    D --> I[Use pip: <br/> pip install helics]
    E --> J(Are you using a <br/> Windows OS?)
    F --> K[Use pkg: <br/> pkg> add HELICS]
    G --> L[Download the pre-compiled <br/> libraries and add them <br/> to your system path, then <br/> build the extension with <br/> SWIG]
    H --> M[Use nimble: <br/> nimble install <br/> https://github.com/GMLC- <br/> TDC/helics.nim#head]
    J -->|Yes| N[Download the pre- <br/> compiled libraries and <br/> add them to your <br/> system path]
    J -->|No| O(Will you be using HELICS <br/> on an HPC System and/or <br/> would you like to use the <br/> spack package installer?)
    O -->|No| N
    O -->|Yes| P[Use spack: <br/> spack install helics]
```

**Comment by nightlark** [comment]
For charts, vegas-lite seems pretty capable (though the source datasets from some of the examples are pretty big).

e.g. combining multiple results into a single layered plot
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "description": "",
  "width": 900,
  "height": 300,
  "data": {
    "url": "https://raw.githubusercontent.com/GMLC-TDC/HELICS-Examples/main/user_guide_examples/advanced/advanced_orchestration/results/peak_power_at_all_evs_10.csv"
  },
  "transform": [
    {
      "lookup": "Hour",
      "from": {
        "data": {"url": "https://raw.githubusercontent.com/GMLC-TDC/HELICS-Examples/main/user_guide_examples/advanced/advanced_orchestration/results/peak_power_at_all_evs_11.csv"},
        "key": "Hour",
        "fields": ["sample_11"]
      }
    },
    {
      "lookup": "Hour",
      "from": {
        "data": {"url": "https://raw.githubusercontent.com/GMLC-TDC/HELICS-Examples/main/user_guide_examples/advanced/advanced_orchestration/results/peak_power_at_all_evs_12.csv"},
        "key": "Hour",
        "fields": ["sample_12"]
      }
    },
    {
      "lookup": "Hour",
      "from": {
        "data": {"url": "https://raw.githubusercontent.com/GMLC-TDC/HELICS-Examples/main/user_guide_examples/advanced/advanced_orchestration/results/peak_power_at_all_evs_13.csv"},
        "key": "Hour",
        "fields": ["sample_13"]
      }
    },
    {
      "lookup": "Hour",
      "from": {
        "data": {"url": "https://raw.githubusercontent.com/GMLC-TDC/HELICS-Examples/main/user_guide_examples/advanced/advanced_orchestration/results/peak_power_at_all_evs_14.csv"},
        "key": "Hour",
        "fields": ["sample_14"]
      }
    },
    {
      "lookup": "Hour",
      "from": {
        "data": {"url": "https://raw.githubusercontent.com/GMLC-TDC/HELICS-Examples/main/user_guide_examples/advanced/advanced_orchestration/results/peak_power_at_all_evs_15.csv"},
        "key": "Hour",
        "fields": ["sample_15"]
      }
    },
    {
      "lookup": "Hour",
      "from": {
        "data": {"url": "https://raw.githubusercontent.com/GMLC-TDC/HELICS-Examples/main/user_guide_examples/advanced/advanced_orchestration/results/peak_power_at_all_evs_16.csv"},
        "key": "Hour",
        "fields": ["sample_16"]
      }
    },
    {
      "lookup": "Hour",
      "from": {
        "data": {"url": "https://raw.githubusercontent.com/GMLC-TDC/HELICS-Examples/main/user_guide_examples/advanced/advanced_orchestration/results/peak_power_at_all_evs_17.csv"},
        "key": "Hour",
        "fields": ["sample_17"]
      }
    },
    {
      "lookup": "Hour",
      "from": {
        "data": {"url": "https://raw.githubusercontent.com/GMLC-TDC/HELICS-Examples/main/user_guide_examples/advanced/advanced_orchestration/results/peak_power_at_all_evs_18.csv"},
        "key": "Hour",
        "fields": ["sample_18"]
      }
    },
    {
      "lookup": "Hour",
      "from": {
        "data": {"url": "https://raw.githubusercontent.com/GMLC-TDC/HELICS-Examples/main/user_guide_examples/advanced/advanced_orchestration/results/peak_power_at_all_evs_19.csv"},
        "key": "Hour",
        "fields": ["sample_19"]
      }
    },
    {
      "lookup": "Hour",
      "from": {
        "data": {"url": "https://raw.githubusercontent.com/GMLC-TDC/HELICS-Examples/main/user_guide_examples/advanced/advanced_orchestration/results/peak_power_at_all_evs_20.csv"},
        "key": "Hour",
        "fields": ["sample_20"]
      }
    },
    {
      "lookup": "Hour",
      "from": {
        "data": {"url": "https://raw.githubusercontent.com/GMLC-TDC/HELICS-Examples/main/user_guide_examples/advanced/advanced_orchestration/results/peak_power_at_all_evs_21.csv"},
        "key": "Hour",
        "fields": ["sample_21"]
      }
    },
    {
      "lookup": "Hour",
      "from": {
        "data": {"url": "https://raw.githubusercontent.com/GMLC-TDC/HELICS-Examples/main/user_guide_examples/advanced/advanced_orchestration/results/peak_power_at_all_evs_22.csv"},
        "key": "Hour",
        "fields": ["sample_22"]
      }
    },
    {
      "lookup": "Hour",
      "from": {
        "data": {"url": "https://raw.githubusercontent.com/GMLC-TDC/HELICS-Examples/main/user_guide_examples/advanced/advanced_orchestration/results/peak_power_at_all_evs_23.csv"},
        "key": "Hour",
        "fields": ["sample_23"]
      }
    },
    {
      "lookup": "Hour",
      "from": {
        "data": {"url": "https://raw.githubusercontent.com/GMLC-TDC/HELICS-Examples/main/user_guide_examples/advanced/advanced_orchestration/results/peak_power_at_all_evs_24.csv"},
        "key": "Hour",
        "fields": ["sample_24"]
      }
    },
    {
      "lookup": "Hour",
      "from": {
        "data": {"url": "https://raw.githubusercontent.com/GMLC-TDC/HELICS-Examples/main/user_guide_examples/advanced/advanced_orchestration/results/peak_power_at_all_evs_25.csv"},
        "key": "Hour",
        "fields": ["sample_25"]
      }
    },
    {
      "lookup": "Hour",
      "from": {
        "data": {"url": "https://raw.githubusercontent.com/GMLC-TDC/HELICS-Examples/main/user_guide_examples/advanced/advanced_orchestration/results/peak_power_at_all_evs_26.csv"},
        "key": "Hour",
        "fields": ["sample_26"]
      }
    },
    {
      "lookup": "Hour",
      "from": {
        "data": {"url": "https://raw.githubusercontent.com/GMLC-TDC/HELICS-Examples/main/user_guide_examples/advanced/advanced_orchestration/results/peak_power_at_all_evs_27.csv"},
        "key": "Hour",
        "fields": ["sample_27"]
      }
    },
    {
      "lookup": "Hour",
      "from": {
        "data": {"url": "https://raw.githubusercontent.com/GMLC-TDC/HELICS-Examples/main/user_guide_examples/advanced/advanced_orchestration/results/peak_power_at_all_evs_28.csv"},
        "key": "Hour",
        "fields": ["sample_28"]
      }
    },
    {
      "lookup": "Hour",
      "from": {
        "data": {"url": "https://raw.githubusercontent.com/GMLC-TDC/HELICS-Examples/main/user_guide_examples/advanced/advanced_orchestration/results/peak_power_at_all_evs_29.csv"},
        "key": "Hour",
        "fields": ["sample_29"]
      }
    }
  ],
  "repeat": {
    "layer":[
      "sample_10", "sample_11", "sample_12", "sample_13", "sample_14", "sample_15", "sample_16",
      "sample_17", "sample_18", "sample_19", "sample_20", "sample_21", "sample_22", "sample_23",
      "sample_24", "sample_25", "sample_26", "sample_27", "sample_28", "sample_29"
    ]
  },
  "spec": {      
      "mark": {
        "type": "line",
        "opacity": 0.4
      },
      "encoding": {
        "x": {"field": "Hour", "bin":{"binned": true, "step":1}, "title":"Hour"},
        "x2": {"field": "Hour"},
        "y": {"field": {"repeat": "layer"}, "type": "quantitative", "title": "kW"}
      }
  }
}
```

**Comment by nightlark** [comment]
The [matplotlib sphinx extension](https://matplotlib.org/sampledoc/extensions.html#inserting-matplotlib-plots) could be interesting; I think a number of our examples use matplotlib already, so this could be a way to run a "ci test" on parts of the example code.

**Comment by trevorhardy** [comment]
I think we should look at this in conjunction with automating the testing of the examples (#1894). 

I like the idea of having output graphs generated as a part of building the documentation. Maybe we have output data files that are created when we run the examples that are an official part of the repository and the input data for these graphs. And this is where the automated testing of the examples comes in: if we can test all the User Guide examples in an automated manner, we can have canonical versions of the results of the examples that get compared any time there is a change to HELICS or the examples themselves. Right now there are several quality-of-life changes that need to be made to many of the examples and it would be great to have a way I could ensure the results before and after the change matches.

**Comment by nightlark** [comment]
The HTML code generated by sphinxcontrib-mermaid results in an exception `Uncaught ReferenceError: mermaid is not defined`

The generated code is:
```
<script src="https://unpkg.com/mermaid/dist/mermaid.min.js"></script>
<script>mermaid.initialize({startOnLoad:true});</script>
```

https://github.com/mgaitan/sphinxcontrib-mermaid/blob/master/sphinxcontrib/mermaid.py has configuration options for changing the javascript used to initialize mermaid, and the version of mermaid to use.

---

I narrowed the issue down to adding the mermaid script after require.js, this breaks:
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js"></script>
<script src="https://unpkg.com/mermaid/dist/mermaid.min.js"></script>
```

And this works:
```
<script src="https://unpkg.com/mermaid/dist/mermaid.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js"></script>
```

**Comment by trevorhardy** [comment]
Mermaid is being used for the installation flowchart in the "docs_v3.3" branch. We'll evaluate if there are other diagrams we should move over to mermaid but for now, I'm going to close out this issue.
