### ISSUE TITLE
Update spack package to support HELICS 3 changes

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/HELICS#2175]
The HELICS spack package needs updating to use the correct arguments and library versions for HELICS 3: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/helics/package.py

Changes needed:
- Use the correct CMake option for enabling variants based on HELICS version being installed (e.g. `ENABLE_ZMQ_CORE` -> `HELICS_ENABLE_ZMQ_CORE`)
- Bump up build dependencies for HELICS 3 installs (cmake 3.10+, c++17 compiler)
- Prevent using Boost 1.77 with HELICS release <=3.0.1
- Disable Python variant for HELICS 3

**Comment by phlptp** [comment]
@nightlark  is this completed?

**Comment by nightlark** [comment]
No, I think there are still options that need updating, including the
removal of some of the swig interfaces.

**Comment by phlptp** [comment]
@nightlark  is this still in progress?

**Comment by nightlark** [comment]
The PR updating the spack package to include renamed options and support for new features is https://github.com/spack/spack/pull/32121

**Comment by nightlark** [comment]
PR updating the spack package has been merged.
