### ISSUE TITLE
Add many HELICS installation videos

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#2202]
Going through the variety of ways you can install HELICS (and get supported language bindings) can be bit confusing as there are many combinations and new users don't necessarily understand HELICS well enough to catch on to subtleties. We should make a set of screencasts to cover various installation/OS combinations.

These could/should include:

Building from source (and modifying cmake options)
Installing with binaries
Incorporating language bindings

**Comment by nightlark** [comment]
Here's an interesting idea: https://asciinema.org/

For markdown we can only include an image linking like this, but on the website we could have an embedded player (homepage for asciinema shows this intro video embedded on the page):
[![asciicast](https://asciinema.org/a/335480.svg)](https://asciinema.org/a/335480)

**Comment by trevorhardy** [comment]
That would work VERY well for the videos where all the work is in the terminal (obviously). Thanks!

**Comment by trevorhardy** [comment]
[YouTube video created and posted.](https://www.youtube.com/watch?v=BSwdT_OAtCU)
