### ISSUE TITLE
Error during compiling: CMAKE_INSTALL_PREFIX is set to nothing

### ISSUE THREAD

**Issue by karuneshm95** [GMLC-TDC/HELICS#2244]
https://github.com/GMLC-TDC/HELICS
karunesh@RADHEYKRISHNA:~/src/HELICS-src/build$ cmake -DBUILD_JAVA_INTERFACE=ON -DBUILD_SHARED_LIBS=ON \-DJAVA_AWT_INCLUDE_PATH=NotNeeded -DHELICS_DISABLE_BOOST=ON \-DCMAKE_INSTALL_PREFIX=$TESP_INSTALL -DCMAKE_BUILD_TYPE=Release ..
-- SYSTEM INFO -> Unix Makefiles  Linux-5.10.16.3-microsoft-standard-WSL2:GNU-9.3.0
-- helics version tag description is develop-g1a0c389e
CMake Warning at CMakeLists.txt:103 (message):
  CMAKE_INSTALL_PREFIX is set to nothing.  If you are using an environment
  variable for handling prefix paths, that variable might not have been set
  before using it with CMake to set the CMAKE_INSTALL_PREFIX option.

-- setting up for GNU on Linux-5.10.16.3-microsoft-standard-WSL2
-- setting helics C++ standard build option to "-std=c++17"
-- Found ZeroMQ library: /usr/lib/x86_64-linux-gnu/libzmq.so
-- Found ZeroMQ headers: /usr/include
-- Module support is disabled.
-- Version: 8.0.1
-- Build type: Release
-- CXX_STANDARD: 17
-- Required features: cxx_variadic_templates
-- JsonCpp Version: 1.9.5
CMake Error at ThirdParty/json_cpp/include/PreventInBuildInstalls.cmake:4 (message):
  The current CMAKE_INSTALL_PREFIX points at the build tree:

    

  This is not supported.
Call Stack (most recent call first):
  ThirdParty/json_cpp/CMakeLists.txt:82 (include)

-- Configuring incomplete, errors occurred!
See also "/home/karunesh/src/HELICS-src/build/CMakeFiles/CMakeOutput.log".
See also "/home/karunesh/src/HELICS-src/build/CMakeFiles/CMakeError.log".

**Comment by phlptp** [comment]
based on the error it looks like CMAKE_INSTALL_PREFIX=$TESP_INSTALL is empty so it it is generating a warning about where to install HELICS which shouldn't be in the build tree.

**Comment by nightlark** [comment]
It looks like jsoncpp makes that a fatal error -- does setting the environment variable `TESP_INSTALL` fix the error?
