### ISSUE TITLE
Iterating during initialization leads to hanging

### ISSUE THREAD

**Issue by eranschweitzer** [GMLC-TDC/HELICS#2342]
**Describe the bug**
When iterating during initialization using (pyhelics) `helicsFederateEnterExecutingModeIterative` the Federates seem to lose sync. 
As a result, it appears that one federate enters execution mode, which the other is still iterating in the initialization.
As a result of this, the federate that enters execution mode gets stuck requesting time and getting an earlier time granted.
The federate that is still in initialization is meanwhile stuck in its call to `helicsFederateEnterExecutingModeIterative`

**What is the expected behavior?**
It would be expected that when all Federates pass `iteration_request_iterate_if_needed` then they would *all* exit the initialization mode together (or step in time together), rather than some moving forward while others continue to iterate.

The motivation is to get the initialization and inter-timestep iterations working.

**To Reproduce**
An example to reproduce the behavior can be found here: https://github.com/GMLC-TDC/HELICS-Examples/tree/iteration/user_guide_examples/advanced/advanced_iteration

The two Federates are `Charger.py` and `Battery.py`. 
Some common functionalities are implemented in `iterutils.py`.
The runner is (unfortunately named) `fundamental_default_runner.json`

**Environment (please complete the following information):**

- Operating System: Windows
- Language Extension: Python
- what compiler or setup process did you use: I installed pyhelics via `pip install helics`
- HELICS version: 

```bash
> helics --version
helics, version 0.6.1

Python HELICS version v3.2.0.post1

HELICS Library version 3.2.0 (2022-05-03)

Python `helics-apps` package not installed. Install using `pip install helics-apps --upgrade`.
```

**Additional context and information**
Documentation about what this particular example is trying to do is described here:
https://github.com/GMLC-TDC/HELICS/blob/iteration_example/docs/user-guide/examples/advanced_examples/advanced_iteration.md

**Comment by phlptp** [comment]
guess we will keep working on this, 
thanks

**Comment by eranschweitzer** [comment]
## Update:

Following conversations with @phlptp a few aspects of how iteration *is intended to work* were clarified:
* There is no general guarantee that Federates will perform the same number of inter-timestep iterations, because these inter -timestep iterations are triggered by new data available to the Federate.
* the intended behavior of the iteration flags is as follows:
    + `force_iteration`: _always_ returns the status flag `ITERATING` basically irrespective of what is going on with other Federates. This flag is supposed to be used only in _rare_ cases.
    + `iterate_if_neede`: is the _general_ iteration flag. The Federate will receive the `ITERATING` flag if there is new data available. As such, to get iteration to work it is critical to _publish first!_ 
* Another way to determine that we are iterating is if `grantedtime == requestedtime`

The general structure of iteration should therefore be:
```
while grantedtime < maxtime:
    helicsPublish
    requestedtime = grantedtime + deltastep
    while True:
        grantedtime, itr_state = helicsFederateRequestTimeIterative(fed, requestedtime,  iterate_if_needed)
        if itr_state == next_step:
            break

        ### Federate code ####
        helicsSubcriptions
        calculate()
        if convergence:
            continue
        else:
            helicsPublish
```

With this structure, I can at least get my example to work.

## Outstanding Issues
* It seems that if the `wait_for_current_time_update` is set to `true` there is an issue exiting iteration during initialization (I had to set it to `false` to make sure the initialization didn't hang
* When requesting the currently granted time, i.e. `requestedtime = grantedtime` the returned iteration flag is always `NEXT_STEP`. 
* There seems to be a counter issue when the iteration number gets very large. The federates simply hang. This seems to be like a 16bit counter overrun issue.
