### ISSUE TITLE
Add CORS for helics broker web server

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#2397]
Currently, this is the `response_ok` when a request is made:

https://github.com/GMLC-TDC/HELICS/blob/55c9c75c3f82c3a8aa18984ea93196f28a8aade4/src/helics/apps/helicsWebServer.cpp#L655-L667

I think we need something like the following code to make the broker web server work in order to access it from the helics-cli web interface

```cpp
    namespace bh = boost::beast::http;
    void add_cors(const bh::request<bh::string_body>& request, bh::response<bh::dynamic_body>& response) {
        auto origin = request[bh::field::origin];
        if (!origin.empty()) {
            response.set(bh::field::access_control_allow_origin, origin);
        }
    }
```

The web interface is at `localhost:3000` (development) or `localhost:5000` (production). I get the following error when I made a request to the broker server:

![Screen Shot 2022-07-11 at 11 22 32 PM](https://user-images.githubusercontent.com/1813121/178414691-29735124-7603-4b4d-b75b-9a670b4e6237.png)

**Comment by phlptp** [comment]
I am not sure how to test that,  Is it something you can make a failing test case for in the repo?
