### ISSUE TITLE
Problem running HELICS - unable to bind zmq reply socket

### ISSUE THREAD

**Issue by abdelrahman-ayad** [GMLC-TDC/HELICS#2462]
New HELICS user. After installation I tried running the fundamental _default example (Battery charger using python federates) as per the tutorial instructions. For some reason the connection can't be established and the broker is unable to connect with the below error. I tried installation on 2 machines (macOS and Linux), with and without docker. I tried playing with the broker address and the port, but still the same error. I tried installing zmq package separately and running basic connection examples and it worked fine. Not sure what's the issue here. 

[info] Running federation: fundamental_default
[info] Running federate broker as a background process
[info] Running federate Charger as a background process
[info] Running federate Battery as a background process
[info] Waiting for 3 processes to finish ...
[error] Process broker has failed, killing other processes
[error] Process broker exited with return code 252
[warn] Last 10 lines of broker.log:
...
[2022-11-02 09:48:31.416] [console] [error] commERROR||30934-oquP2-l8pMa-aMh1d-0V4f3 (1)[connecting]::Unable to bind zmq reply socket giving up tcp://127.0.0.1:23405
[2022-11-02 09:48:31.416] [console] [error] commERROR||30934-oquP2-l8pMa-aMh1d-0V4f3 (1)[connecting]::receiver connection failure
Broker is unable to connect

![Screen Shot 2022-11-02 at 9 50 37 AM](https://user-images.githubusercontent.com/70848794/199506769-a57a285e-50b9-45a6-b1e1-f8173a783e96.png)

**Comment by trevorhardy** [comment]
Let me try this on my machine and see if I can replicate the error.

**Comment by trevorhardy** [comment]
@abdelrahman-ayad, while I'm working to get this set up on my end (just switched to a new computer yesterday and still getting my environment put back together), is there anything interesting in the Charger or Battery logs?

**Comment by abdelrahman-ayad** [comment]
I am attaching screenshots of the log files for the broker, charger and Battery. Not sure what to make of the connected status with broker state=-3
<img width="973" alt="Screen Shot 2022-11-02 at 11 57 02 AM" src="https://user-images.githubusercontent.com/70848794/199539337-0f555e73-4f12-4a71-9040-cab9b2c5c092.png">
<img width="1007" alt="Screen Shot 2022-11-02 at 11 57 10 AM" src="https://user-images.githubusercontent.com/70848794/199539344-ce842417-f914-4fee-8c27-a3e14c1ab415.png">
<img width="1327" alt="Screen Shot 2022-11-02 at 11 57 22 AM" src="https://user-images.githubusercontent.com/70848794/199539348-72a5b22f-7bff-42f9-b00e-198f91941eb7.png">

**Comment by abdelrahman-ayad** [comment]
Quick update: I was able to run the above examples successfully on a windows machine. So far the problem is with Linux and macOs. 

> Let me try this on my machine and see if I can replicate the error.

**Comment by trevorhardy** [comment]
OK, I've got this working on my Mac. Here's my system:

Architecture: x_86 (Intel)
OS: 10.15.7
HELICS version: 3.3.0
Python version: 3.10.6

None of this should matter except maybe the processor architecture. I know I'm having trouble right now getting PyHELICS to work on my ARM-based Mac.

What are the details of your system?

**Comment by trevorhardy** [comment]
If you have the time, we have office-hours today three hours from now (11am PT). If you want to join, email me at trevor.hardy@pnnl.gov and I'll send you the invitation.

**Comment by abdelrahman-ayad** [comment]
Problem solved, thanks to Trevor and Philip. The default port was blocked (used by another broker or program), so I had to specify the --port flag to another port, and add broker_port field in each federeate json file.
