### ISSUE TITLE
Python Pi-exchange error (zmq broker connection timed out)

### ISSUE THREAD

**Issue by saheb26-dev** [GMLC-TDC/HELICS#2476]
I'm trying the Pi exchange example ([https://docs.helics.org/en/helics2/introduction/python.html]) and I'm getting the following error message. 
![Pisenderreciever](https://user-images.githubusercontent.com/107430234/203166109-02858b06-2a0a-476e-aebb-fd837b8c58f8.PNG)

Operating system: Rocky Linux 9
HELICS version: 3.3.1

**Comment by nightlark** [comment]
The page you are looking at appears to be for an older version of HELICS (v2). Anyway, the issue is you need to start a helics_broker either directly, or using the broker.py script included with the example code in https://github.com/GMLC-TDC/HELICS-Examples/tree/main/python/pi-exchange

**Comment by trevorhardy** [comment]
Closing issue as it appears the suggestion has worked.
