### ISSUE TITLE
Translator json configuration

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#2543]
make sure the translator configuration is supported through JSON

  "translators": [
     {
       "name": "test translator",
       "source_target": name or key, (string)
       "destination_target: name or key, (string)
       "type": "JSON"
     }
  ]

**Comment by trevorhardy** [comment]
Probably need to add the "global": true/false flag to the above.

**Comment by trevorhardy** [comment]
And since we have [the API](https://python.helics.org/api/capi-py/#helicsTranslatorSetInfo), translators support the "info" field as well.

**Comment by trevorhardy** [comment]
And the `source_target` and `destination_target` can be lists, right?

**Comment by phlptp** [comment]
closed in #2560
