### ISSUE TITLE
Migrate ReadTheDocs configuration from web interface to .readthedocs.yaml

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/HELICS#2549]
Several configuration options configured on the ReadTheDocs website are being removed in September this year. The settings for these options should be moved to the `.readthedocs.yaml` file instead. https://blog.readthedocs.com/migrate-configuration-v2/

The current settings there are:
```
Documentation type
Sphinx Html

Requirements file
docs/requirements.txt

Python Interpreter
CPython 3.x

Enable PDF build

Enable EPUB build
```

**Comment by trevorhardy** [comment]
The existing .readthedocs.yaml appears to have all of this covered. There is a test "blackout" on July 24th 2023 that will use the .readthedocs.yaml and not support the deprecated version. I'm closing this issue and if our docs build fails during that period we can reopen.
