### ISSUE TITLE
quick links on the user-guide side bar shows 404 error

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#2551]
https://docs.helics.org/en/latest/quick-links.html

The side bar on the user guide shows a HELICS 404 instead of the subtopics.  The link still works and the page shows but not on the sidebar.

**Comment by trevorhardy** [comment]
Fixed with PR #2552

For reasons I don't know, the "HELICS 404" was hard-coded in the side-bar. 🤷‍♂️
