### ISSUE TITLE
helics::systemInfo() is not exported to the shared library

### ISSUE THREAD

**Issue by pdbj** [GMLC-TDC/HELICS#2572]
**Describe the bug**
The function referenced is not marked for export, so it's present in the shared library only as a local symbol, and can't be linked.

**What is the expected behavior?**
Function should be marked for export.

**To Reproduce**
```cpp
#include "helics/helics.hpp"

#include <iostream>

int main(int argc, char **argv)
{
  auto info = helics::systemInfo();
  std::cout << info << '\n';
}
```

This will compile because the function is present in `helics/core/helicsVersion.hpp` but linking fails:

```sh
g++ -std=c++17 -IHELICS/build/include/helics_cxx -LHELICS/build/lib -lhelicscpp-apps -lhelicscpp -lhelics    system-info.cc   -o system-info
/usr/packages/gcc/gcc-12.1.1/bin/ld: /var/tmp/cc0vnirF.o: in function `main':
system-info.cc:(.text+0x18): undefined reference to `helics::systemInfo[abi:cxx11]()'
collect2: error: ld returned 1 exit status
make: *** [<builtin>: system-info] Error 1
```

The symbol is present in as a local `t` in `libhelics.so`:
```
$ nm -C build/lib/libhelics.so | grep systemInfo
00000000000b4590 T helicsGetSystemInfo
000000000005fbf1 t helicsGetSystemInfo.cold
000000000059f3a8 b guard variable for helicsGetSystemInfo::systemInfo
0000000000336350 t helics::systemInfo[abi:cxx11]()
0000000000096641 t helics::systemInfo[abi:cxx11]() [clone .cold]
000000000059f3c0 b helicsGetSystemInfo::systemInfo
```

**Environment (please complete the following information):**

- Operating System: Linux
- Language Extension: C++
- what compiler or setup process did you use: g++-12.1.1
- HELICS version: 3.4.0 (2023-01-19)"

**Additional context and information**

**Comment by nightlark** [comment]
@phlptp can this issue be closed?

**Comment by phlptp** [comment]
Yes

---
Sent from Workspace ONE Boxer<https://whatisworkspaceone.com/boxer>
On January 31, 2024 at 9:48:09 AM PST, Ryan Mast ***@***.***> wrote:

@phlptp<https://urldefense.us/v3/__https://github.com/phlptp__;!!G2kpM7uM-TzIFchu!33MQwa-VfZHLueJ4l7AhfGJrCnv9P9eQ1Rt-sugU_lDNkADYamD9OG6XlxsnA2YTsM3ngM9M1EgDtK-bS09kdzw$> can this issue be closed?
