### ISSUE TITLE
Missing APIs for existing helicsDataBuffer...() APIs

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#2573]
**Describe the bug**
There are several existing APIs in the `helicsDataBuffer...()` family but most if not all take a `helicsDataBuffer` object. In the existing C-based APIs (such as Python) there is not a way to get a DataBuffer object.

**What is the expected behavior?**
A dedicated API to get `helicsdataBuffer` objects associated with HELICS interfaces (handles) is needed for use with these APIs.

**Comment by phlptp** [comment]
Closed in #2587
