### ISSUE TITLE
Problem running Brokers - Multi-computer Co-simulation example unable to bind zmq reply socket

### ISSUE THREAD

**Issue by CheungBok** [GMLC-TDC/HELICS#2577]
I tried to run the Brokers - Multi-computer Co-simulation example as tutorial instructions. I run this example in two servers. The server A contains the computer1 folder files and server B contains the computer2 folders. In this example, server A contains charger and controller and server B has Battery and broker. For the server A, I followed the instructions from tutorial that changed the "broker_address" flag of the ChargerConfig.json and ControllerConfig.json files. And do nothing for the server B. For some reason the connection between server A and B can not be established. Battery can bind into the broker but the charger and controller from server A cannot bind the broker. I also installed the zmq python package and run client and server connection between the two servers and it worked well. 
<img width="991" alt="error" src="https://github.com/GMLC-TDC/HELICS/assets/38665014/ca95e394-c9d1-4d57-974c-9fd935e138b4">

Server A:
[info] Running federation: Controller_and_Charger
[info] Running federate Charger as a background process
[info] Running federate Controller as a background process
[info] Waiting for 2 processes to finish ...
[error] Process Charger exited with return code 1
[warn] Last 10 lines of Charger.log:
...
[2023-12-16 14:52:22.342] [console] [warning] _core_BhJka1 (0)[connected]::broker state=-3, broker id=0, sleepcnt=297
[2023-12-16 14:52:22.442] [console] [warning] _core_BhJka1 (0)[connected]::broker state=-3, broker id=0, sleepcnt=298
[2023-12-16 14:52:22.543] [console] [warning] _core_BhJka1 (0)[connected]::broker state=-3, broker id=0, sleepcnt=299
[2023-12-16 14:52:22.643] [console] [warning] _core_BhJka1 (0)[connected]::broker state=-3, broker id=0, sleepcnt=300
Traceback (most recent call last):
  File "/home/cust1/multi_computer/computer1/Charger.py", line 142, in <module>
    fed = h.helicsCreateCombinationFederateFromConfig("ChargerConfig.json")
  File "/home/cust1/anaconda3/envs/ds/lib/python3.9/site-packages/helics/capi.py", line 3723, in helicsCreateCombinationFederateFromConfig
    raise HelicsException("[" + str(err.error_code) + "] " + ffi.string(err.message).decode())
helics.capi.HelicsException: [-1] core is unable to register and has timed out, federate cannot be registered
...
[error] Process Controller exited with return code 1
[warn] Last 10 lines of Controller.log:
...
[2023-12-16 14:52:22.220] [console] [warning] _core_KXAOZY (0)[connected]::broker state=-3, broker id=0, sleepcnt=297
[2023-12-16 14:52:22.320] [console] [warning] _core_KXAOZY (0)[connected]::broker state=-3, broker id=0, sleepcnt=298
[2023-12-16 14:52:22.420] [console] [warning] _core_KXAOZY (0)[connected]::broker state=-3, broker id=0, sleepcnt=299
[2023-12-16 14:52:22.520] [console] [warning] _core_KXAOZY (0)[connected]::broker state=-3, broker id=0, sleepcnt=300
Traceback (most recent call last):
  File "/home/cust1/multi_computer/computer1/Controller.py", line 49, in <module>
    fed = h.helicsCreateMessageFederateFromConfig("ControllerConfig.json")
  File "/home/cust1/anaconda3/envs/ds/lib/python3.9/site-packages/helics/capi.py", line 3678, in helicsCreateMessageFederateFromConfig
    raise HelicsException("[" + str(err.error_code) + "] " + ffi.string(err.message).decode())
helics.capi.HelicsException: [-1] core is unable to register and has timed out, federate cannot be registered

Server B (keep waiting):
[warn] helics-cli's web interface is not installed. You may want to run `pip install "helics[cli]"`.
[warn] helics-cli's observer functionality is not installed. You may want to run `pip install "helics[cli]"`.
[info] Running federation: Battery
[info] Running federate broker as a background process
[info] Running federate Battery as a background process
[info] Waiting for 2 processes to finish ...

- Operating System: Linux
- Language Extension: Python
- what compiler or setup process did you use: pip install helics
- HELICS version: 3.4.0

**Comment by trevorhardy** [comment]
Dealing with networking problems is always a challenge. 

Good idea on testing networking in general between server A and B using ZMQ. Here's a few things to try:

1. Try setting the `core_type` in all the config files to `zmq_ss` and instantiating the broker with`-t zmq_ss`. This core uses only a single socket and can be helpful in debugging or working around network problems.
2. Try setting the broker port explicitly. You can see the instructions in the [example page in the documentation](https://docs.helics.org/en/latest/user-guide/examples/advanced_examples/advanced_brokers_multicomputer.html).

**Comment by CheungBok** [comment]
Thank you for your time. Updated:
1. When I changed it to the zmq_ss flag, the servers can establish connection and the co-simulation run normally. 
2. Changing port does not help. 

For the Brokers-Multi-Protocol Brokers scenarios, I tried to put them into different servers and run a co-simulation. But it still generates errors. Server A contains brokerA.json, Server B contains brokerB.json & battery files, and Server C contains brokerC.json, charger and controller files. The overview settings are: battery bind to brokerB, charger and control bind to brokerC, and brokerA are the parent of brokerB and brokerC. The log files demonstrate brokerA, B, C are connected but battery, controller and charger cannot connect to their corresponding broker. And I tried to use different core_type, including tcp, zmq_ss, zmq and still gets the same error messages.

<img width="728" alt="error" src="https://github.com/GMLC-TDC/HELICS/assets/38665014/810e47d0-5200-4576-bf4e-da21f39a8c0e">

<img width="723" alt="error2" src="https://github.com/GMLC-TDC/HELICS/assets/38665014/24ddd9bc-541c-4c6c-b062-1bb7a85b7d9e">

**Comment by trevorhardy** [comment]
Are you talking about the [multi-protocol example](https://docs.helics.org/en/latest/user-guide/examples/advanced_examples/advanced_brokers_multibroker.html) or the [broker hierarchy example](https://docs.helics.org/en/latest/user-guide/examples/advanced_examples/advanced_brokers_hierarchies.html)?

**Comment by trevorhardy** [comment]
Double check that you don't have any lingering brokers from running previous examples; if you do, end them all before you try running the example again. The brokers connecting to each other is the hard part; a federate should be able to connect to the broker on its same machine.

**Comment by CheungBok** [comment]
Sorry for the misunderstanding. The brokers are able to connect on the same machine. 

I tried to reproduce the [broker hierarchy example in difference servers](https://docs.helics.org/en/latest/user-guide/advanced_topics/broker_hierarchies.html). I would like to build something similar as the below graph.  
<img width="591" alt="overview" src="https://github.com/GMLC-TDC/HELICS/assets/38665014/beb9d9f2-a617-479e-b11e-56326bfa678a">

Because I did not find the example code, I try to reproduce it by the [broker hierarchy example](https://docs.helics.org/en/latest/user-guide/examples/advanced_examples/advanced_brokers_hierarchies.html). Then I distribute the code into 3 servers. The server settings are below:
--Server A: brokerA.json(--ipv4)
--Server B: brokerB.json(--brokeraddress=tcp://serverA)    and battery.py & battery.json
--Server C: brokerC.json(--brokeraddress=tcp://serverA)    and controller & charger(.py and .json)

**Comment by CheungBok** [comment]
I change the loglevel flag from warning to trace. In the log file, the results show:

1. the federates can not connect to their respective brokers.
2. the brokerB and brokerC are able to connect to brokerA. But the connection between them seems to be abnormal.

ServerA error message: (brokerA.log)
<img width="853" alt="brokerA" src="https://github.com/GMLC-TDC/HELICS/assets/38665014/e853ce83-3873-4db0-a879-a7365287bbe5">

ServerB error message: (brokerB.log)
<img width="846" alt="brokerB" src="https://github.com/GMLC-TDC/HELICS/assets/38665014/9798c52f-8826-409a-b7c5-4ae38d338064">

ServerC error message: (controller.log and brokerC.log)
<img width="790" alt="controller" src="https://github.com/GMLC-TDC/HELICS/assets/38665014/ef131c29-4338-4d91-9d4e-da65a2b0ea19">
<img width="800" alt="brokerC" src="https://github.com/GMLC-TDC/HELICS/assets/38665014/feea9641-74e4-42fa-9cd2-4de2cbf15861">

**Comment by trevorhardy** [comment]
I'm not entirely sure that there is a problem in the broker connections but without the federates connecting, its hard to tell. Let's work on getting the federates connecting, starting with Battery which is trying to connect to brokerB.

The runner JSONs in the hierarchy example have a number of flags to set for each broker; are you using all of those flags when you start up each broker. In particular, setting  `--port=` defines the port the federates try to connect to the broker on and it that's missing they won't be able to connect. Similarly, the battery federate needs to have its `broker_address` parameter set correctly in its config JSON.

**Comment by CheungBok** [comment]
The --broker_address of Battery, Controller and Charger is tcp://127.0.0.1. Also, I tried different settings, including w/o --port flag, allocating into different ports, but it did not work.  

Besides, there is a python indentation error in the [broker hierarchy example](https://github.com/GMLC-TDC/HELICS-Examples/blob/main/user_guide_examples/advanced/advanced_brokers/hierarchies/Battery.py#L46C1-L46C27).

**Comment by trevorhardy** [comment]
So you're doing like the example does and have the BatteryConfig.json with `"broker_address": "tcp://127.0.0.1:25300"` and you're instantiating brokerB with `--port=25300`? This will only work if both the Battery federate and brokerB are on the same computer. IP address 127.0.0.1 is called a loop-back address and is used for communication that originates and terminates on the same machine. When connecting the brokers together across machines, brokerB will have a broker address using the IP of the machine brokerA is on; for example `--broker_address=tcp://130.20.81.128:25200`. The broker hierarchy example is written assuming all the brokers are running on a single machine so the IP addresses are all 127.0.0.1. In your case, those addresses will be different.

**Comment by CheungBok** [comment]
Thank you for your explanation.
