### ISSUE TITLE
helics_player not keeping separate tags

### ISSUE THREAD

**Issue by temcdrm** [GMLC-TDC/HELICS#2601]
**Describe the bug**
A player file with 6 different publications is actually publishing them all under the same tag.  The values and timings are correct, but it's publishing under 1 tag, which is neither the first nor last encountered in the player file. This example used to work.  We could organize the player file in separate sections for each publication, and the player seemed to sort them correctly by time, and publish values under the correct tag. I don't have a workaround yet.

**To Reproduce**
This is a minimal test case: https://github.com/pnnl/pecblocks/tree/master/examples/helics/test. It's under a Python project but you don't need Python or any modules, just the HELICS apps.

**Environment (please complete the following information):**
HELICS 3.4 binaries on Windows and Linux.

**Comment by phlptp** [comment]
Thank you for identifying this issue.    It appears to be an issue with the use of local and the use of text file input.   This was an oversight in testing for that combination.   A test has been added and a fix included.

**Comment by temcdrm** [comment]
Thanks.  Do you know when this will show up in a binary release?  And in the Python Helics module?
