### ISSUE TITLE
Update HELICS minimum build requirements

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/HELICS#2637]
Update HELICS minimum build requirements to align with Ubuntu 22.04
- Dependencies
- Compilers
- Compiler flags
- CMake version

(Check docs for roadmap to see if there are details on this)

**Comment by phlptp** [comment]
Tentative plans include

GCC 11
clang 14
CMake 3.22
MSVC 16.10
XCode 14

**Comment by phlptp** [comment]
#2674 does most of this for a 3.6 release
