### ISSUE TITLE
Fix build warnings in 3.5.2 from GCC/12

### ISSUE THREAD

**Issue by pdbj** [GMLC-TDC/HELICS#2657]
**Describe the bug**
A handful of compiler warnings from GCC/12 (with web server disabled)

Patch attached.

**Environment (please complete the following information):**

- Operating System: Linux
- Compiler: GCC/12.1.1
- HELICS version: 3.5.2

[helics-3.5.2-gcc-12.patch](https://github.com/GMLC-TDC/HELICS/files/15492225/helics-3.5.2-gcc-12.patch)

**Comment by phlptp** [comment]
These issues should be fixed in the latest release.  Thanks for the patch.
