### ISSUE TITLE
fails to build with external fmt-11

### ISSUE THREAD

**Issue by MehdiChinoune** [GMLC-TDC/HELICS#2668]
**Describe the bug**
Fails to build with fmt-11

**What is the expected behavior?**
buils

**To Reproduce**
Build and Install fmt-11
build againati it

**Environment (please complete the following information):**

- Operating System: all
- Language Extension: C/C++
- what compiler or setup process did you use: GCC
- HELICS version: 3.5.3

**Additional context and information**

**Comment by phlptp** [comment]
This will be fixed in the 3.6 release.  Later September or early October.   Thanks
