### ISSUE TITLE
Failure to send very large messages via endpoints

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#2698]
**Describe the bug**
At very large message sizes (~100Mbytes), HELICS fails to deliver the entire message and does not throw an error.

**What is the expected behavior?**
Entire messages would be delivered or an error would be thrown indicating not all the message was received.

**To Reproduce**
Test federation is included in the [HELICS-Examples repo](https://github.com/GMLC-TDC/HELICS-Examples/tree/92ccf846058b7d6f65d88a530bb4673379c59aa3/unmaintained/python/helics_message_size). 

**Environment (please complete the following information):**

- Operating System: tested on macoS
- Language Extension: Python
- what compiler or setup process did you use: built 3.5.3 from source
- HELICS version: 
```
helics, version v3.5.3

Python HELICS version v3.5.3

HELICS Library version 3.5.3 (2024-07-08)
```

**Additional context and information**
Sender log:
```
Sent message of length 1000
Sent message of length 10000
Sent message of length 100000
Sent message of length 1000000
Sent message of length 10000000
Sent message of length 100000000
Sent message of length 1000000000
```

Receiver log:
```
Full message received of size 1000
Full message received of size 10000
Full message received of size 100000
Full message received of size 1000000
Full message received of size 10000000
Incomplete message received of size 16113920 out of 100000000
Incomplete message received of size 10144256 out of 1000000000
```

**Comment by leovsch** [comment]
I've also ran the example in my environment:

- Operating System: tested on windows 11
- Language Extension: Python
- what compiler or setup process did you use: installed pip package
- HELICS version:


```
helics, version v3.5.3

Python HELICS version v3.5.3

HELICS Library version 3.5.3 (2024-07-08)
```

The result was the same as in the issue description.

**Comment by trevorhardy** [comment]
Confirmed on the 3.6.0 develop library that all the long messages in the above test are received:

```
(helics_dev) hard312@WD86465 helics_message_size % less long_message_receiver.log

Full message received of size 1000
Full message received of size 10000
Full message received of size 100000
Full message received of size 1000000
Full message received of size 10000000
Full message received of size 100000000
Full message received of size 1000000000
```
