### ISSUE TITLE
Use `install_name_tool` in CMake to set rpath paths in executables

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#409]
Currently CMake adds or appends the correct rpaths. It should additionally change the existing dependencies to `@rpath/library` to ensure that it works across different configurations across machines.

See the following for reference:

https://github.com/GMLC-TDC/HELICS-src/blob/7d17a60/scripts/fix_install_names.py#L42-L58

**Comment by phlptp** [comment]
@nightlark @kdheepak is this needed anymore or still something we need to work on?

**Comment by kdheepak** [comment]
I think the zmq libraries now are correct, so this has been fixed sometime along the way. I haven’t checked the other dependencies.
