### ISSUE TITLE
Weekly run with Octave?

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#421]
We should probably have some testing done with Octave once the test cases are established.  The question is how much time does it take to set up octave, and which branch do we want to do that one in the CI testing.

**Comment by bpalmintier** [comment]
I like the idea, though think it would be best if we can share much of the tests with MATLAB, which I expect more folks will use. I understand that the semantics of connecting to the shared library are quite different between the platforms, but the rest of the code should be interchangeable. This could be achieved by trying to put the Octave vs. Matlab differences that the user would see in a commonly named (set of?) function(s), perhaps `helicsStartup.m` 

Then perhaps the test functions (and examples) can be written in a way that works on both allowing automated CI to track them with Octave, and occasional (pre release?) manual checks with MATLAB (along with other non-CI checks such as multi-machine)

**Comment by phlptp** [comment]
My expectation is that the actual code will be pretty much identical, with the exception that the unit test frameworks between matlab and octave are distinct and very different, so if we want to take advantage of them instead of writing our own test framework, they will need to be distinct.    I have seen a few libraries that unify them but then we would need to add another library to the HELICS code.

**Comment by bpalmintier** [comment]
Ah, yes I see that now. I do like the simplicity of octave's `%!` based tests, too bad MATLAB (or someone in MATLAB central) hasn't followed suit.

I wonder if we can try to make their test suites use a common file that implements the core of any complex tests in the same way (e.g. setup, teardown, etc.) such that each unit framework is basically only calling these shared functions.

**Comment by phlptp** [comment]
octave test set up with docker in circleCI
