### ISSUE TITLE
Co-sim diagnostics

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#438]
One of the comments and discussions on the scalability webinar was about diagnostics that could give users insight into the performance and bottlenecks in the co-simulation as a whole.  

So this is opening a discussion on what those diagnostics might look like in a little more details.  
What information would be useful to someone running a larger co-simulation  and how should that information be extracted and presented to a user?

**Comment by abhyshr** [comment]
At a minimum, I think I would want to know how much time is spent on HELICS calls and domain simulator calls. Having the number of function calls would also be helpful. Having some sort of tabulated output, ala gprof, would be nice. Macro-level logging by stages (creation, initialization, execution, destruction) could also be helpful.

**Comment by phlptp** [comment]
What do you mean by number of function calls?

**Comment by trevorhardy** [comment]
Are we considering "diagnostics" as equivalent to or including "trouble-shooting" tools intended to get a federation running properly? Or are "diagnostics" more orientated towards performance improvements?

**Comment by abhyshr** [comment]
I meant the number of times each function is called.

**Comment by phlptp** [comment]
which functions would you be concerned with?  I am assuming the number of times things like getSubscriptionUnits or similar function is not of interest.  But I am not clear where a line would be between functions of interest and those not of interest.  There are a few functions you really only call once per federate so I am not sure those are of interest either.

**Comment by phlptp** [comment]
@trevorhardy,  I am not sure,  the complete target of the diagnostics.  there was some comments on the review meeting about diagnostics and I want to drill down a little further in a discussion of what that might mean.  I remember the conversation being in reference to co-sim performance,  not necessarily HELICS performance itself but getting a sense of what the slowest federate was and perhaps how much parallelism a particular federation was getting.

**Comment by trevorhardy** [comment]
@phlptp That was my impression as well; the comments seemed geared towards improving the performance of an existing working federation and less about ensuring the federation was functioning properly. In our work with FNCS to date we've spent most of our time trying to get the federation assembled correctly, making sure the right messages and values were being passed at the right time. I cases where you're running more than two or three federates, this is a more fundamental need and I think should be a higher priority. Once the federation is up and running consistently, that is the time to start focussing on optimization and improving performance and the need for diagnostics becomes more pressing (which federate is taking the longest, how long does it take to move from time-step to time-step, etc...).

To state my view concisely, I think there are features we should be adding to support debugging and trouble-shooting of a federation prior to adding features that support monitoring and optimization of a federation.

**Comment by phlptp** [comment]
What features could you see as being useful for debugging/trouble shooting a federation?

**Comment by phlptp** [comment]
Are there any things from your experience with FNCS that would have been helpful had they been available, or were available and are not in HELICS?

**Comment by trevorhardy** [comment]
FNCS had little to no support for the kinds of things that would have made trouble-shooting much more efficient. It did have the bare-bones, though: a tracer "simulator", player "simulator" (both distributed with the FNCS itself) and per-federate logging capabilities. These simple tools enabled us to eventually solve problems but they didn't make it easy. We would do things like run a federation, kill it early, open up a big log file and start tracing through it, looking for messages that seemed to be in the wrong place or had the wrong value. Everything was done in a piece-meal, unintegrated fashion and it was very labor intensive.

What would have been useful would have been the kinds of things the IDEs for traditional programming offer: ability to manually control the time of the federation (stopping at a certain time, stepping one time-grant at a time), ability to watch the values that are flowing between federates, and doing this in an integrated manner.

**Comment by nightlark** [comment]
Something like TotalView's MPI/parallel job debugging would be neat.

**Comment by trevorhardy** [comment]
I have no direct experience with TotalView but after looking over the documentation briefly, it is clear they have been able to address handling multiple compute nodes and each nodes processes. I've been struggling to understand how to do this in a scalable way and I bet there are some lessons to be learned from TotalView. Thanks for the suggestion, @nightlark.

**Comment by trevorhardy** [comment]
I'll add a second to @abhyshr desire for some profiling that shows how much time is being spent in various stages of execution of the federation. Off the top of my head everything would be sorted into these stages:

1. **Native federate execution time** (as if the federate was not in a co-simulation).
2. **HELICS messaging time** - how long it is taking to send and receive messages. For most federates this probably will be trivial but there are some edge cases where it might be important to be able to see the value.
3. **Time request waiting** - time spent by the federate waiting to receive a time grant. In most cases this will be time spent waiting on other federates but in some edge cases it may include processing time by HELICS cores and/or brokers.

There are probably similar times that relate to cores and broker but not knowing the architecture super well, I'll leave it up to somebody else to figure out what those categories should be. I speculate that users would only be interested in these details if experimenting with core types or broker topologies to optimize their co-simulation. Probably most of the time this would be largely used by developers to optimize HELICS proper.

I'm assuming it would make most sense to have this profiling off by default unless the overhead is trivial.

**Comment by trevorhardy** [comment]
The profiling that @kdheepak is wrapping up is a good start on this work.

**Comment by phlptp** [comment]
I think between the profiling capability and the visualizations in the helics runner this is mostly addressed so I am going to close it.
