### ISSUE TITLE
Documentation is lacking

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#489]
Those that are new to HELICS and attempting to integrate a new simulator are finding the documentation lacking and being forced to examine the source code to understand what the APIs are doing and if they will be useful in a particular case. This is a clear sign that the documentation is currently not adequate. 

In a recent conversation with @phlptp I agreed to try to write the documentation for the major APIs as a part of the User Guide. I'm still planning on doing that but feel that we need to put a major effort into more thoroughly documenting ALL the APIs. Those individuals that I've been working with here are PNNL that are just starting on HELICS are finding the lack of documentation very difficult to work around and it make the on-ramp to HELICS very steep. 

We can discuss as a team where this fits into the priorities but it seems to me we are close to having v2 of HELICS running but a LONG ways from being ready for those currently outside the HELICS development community to adopt and use it without significant support directly from developers.

**Comment by nightlark** [comment]
Areas that could use changes based on feedback:
- supported publication type strings (double, vector of doubles, etc) and how to access data types published using non-C++ language interfaces
- CSharp -> C#

**Comment by phlptp** [comment]
I think we did quite a bit in 2.0 but more is probably needed so I am moving the issue to 2.X

**Comment by nightlark** [comment]
Two things to make sure are documented:
1. Clarify that `coreinitstring` format is just command line arguments
2. Options to use with multiple users running HELICS on the same machine (separate simulations)

**Comment by phlptp** [comment]
This issue is old and vague, so I am going to close it in favor of more specific deficiencies in the documentation as they come up.  There are a few items in this discussion that will be broken out into separate issues.
