### ISSUE TITLE
Include commit hash in HELICS version string

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/HELICS#498]
**Is your feature request related to a problem? Please describe.**
The HELICS version number and date strings rely on manually updating the CMakeLists.txt file for new releases. For build artifacts from CI, distinguishing which commit it originated from (ex: in a log file) is impossible for later reproducing the build.

**Describe the solution you'd like**
Add an option to include a commit hash as part of the version string (to the HELICS 2.0 branch).

**Comment by phlptp** [comment]
This is the same as #376.    The real question is how to do we do this but only have the regular release number show up for any users?

**Comment by kdheepak** [comment]
This is what I've used in the past and it reads well I think.

```
    const version_string = compile_time_exec("git describe --tags HEAD", DEFAULT_VERSION_NUMBER)
```

**Comment by nightlark** [comment]
The compile_time_exec solves the problem with a cmake-only solution of ensuring that the version string is up to date if new commits get pulled without re-running cmake.
