### ISSUE TITLE
Best Practices for cmake directories

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#499]
Based on some review of best practices for CMAKE folder organization, we should consider having our /src, /test,  /interfaces folders be able to be used in a standalone context.    So essentially someone could pull out those folders and generate a project from them with CMAKE without the root folder.

**Comment by nightlark** [comment]
Do you have links to some reading on cmake folder organization? I've thought some about how an interface could be separate from the main HELICS repository.

**Comment by phlptp** [comment]
file:///C:/Users/top1/Downloads/git_cmake_conan_how_to_ship_and_reuse_our_cpp_projects__mateusz_pusz__cppcon_2018.pdf  starting around 18 for the cmake stuff.  But the whole presentation is mostly about conan, which we probably want to look at at some point in the not too distant future.

**Comment by nightlark** [comment]
Another thing we should consider doing for the interfaces is make it possible to add additional language interfaces either by checking them out as a subfolder of interfaces, or otherwise create a new interface using the existing shared swig files as a base (I guess that then any tests for a language binding should live within the folder for that interface)

**Comment by nightlark** [comment]
Similar separation for different core types could also be useful -- either to enable easier development of 3rd party core types, or to have better separation of dependencies for a particular core from the rest of the code.

**Comment by nightlark** [comment]
The way it works with llvm is that the extras get checked out into a subfolder, and then you'd run cmake for the root llvm project and build as usual. The other way would be plugins/shared libraries like GridLab-D.

With either approach, each core is responsible for finding libraries it needs (the ZeroMQ core takes care of finding libzmq, other parts of HELICS don't need to know about libzmq).

**Comment by phlptp** [comment]
I think we are getting progress toward this issue.  I think at some point we should make the src/helics folder capable of a standalone cmake build.  At that point I think we could close this issue.
