### ISSUE TITLE
Fix installation on linux using conda for helics 1.3.1

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#532]
Currently, Travis builds for the conda package on v1.3.1 fail.

See https://www.travis-ci.org/kdheepak/helics-conda/builds/439232945

**Comment by phlptp** [comment]
@kdheepak  what is the status of this issue?

**Comment by phlptp** [comment]
Is it relevant any more?

**Comment by nightlark** [comment]
I'd be inclined to say no... people should probably be using or have switched to 2.x by now. And there's some reports that multi-host simulations on Linux have issues in 1.3.x that would make it undesirable to use.

**Comment by phlptp** [comment]
OK, when we release 2.1 we will close this and make a statement that anything before 2.0 is no longer supported and won't be fixed.

**Comment by phlptp** [comment]
We are no longer supporting any release before 2.0.0
