### ISSUE TITLE
Make MATLAB extension installation from source more streamlined

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#537]
Perhaps just add the following to the documentation:

```
$  cp /path/to/cmake-3.12/Modules/FindMatlab.cmake ../cmake/MATLABConfig.cmake
$  cp /path/to/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake ../cmake/
$  cp /path/to/share/cmake-3.12/Modules/FindPackageMessage.cmake ../cmake/
$  export MATLAB_DIR=/path/to/gitrepos/HELICS-src/cmake/
```

**Comment by phlptp** [comment]
I don't understand why this is necessary,  it certainly hasn't been when I have built and installed this?  @nightlark  have you had to do any of this?    We should not be copying cmake modules that are in the core cmake directories.

**Comment by nightlark** [comment]
I haven't encountered problems like this, but I haven't done much with the Matlab interface.

**Comment by nightlark** [comment]
I think I found the problem -- it should be find_package(Matlab). Probably doesn't care about the case on Windows.

**Comment by kdheepak** [comment]
We have to use the files included in this repo and not use swig to generate the files.

**Comment by nightlark** [comment]
@kdheepak Did that take care of the problem with needing to copy files?

Also, is there a reason why we are distributing a copy of FindMatlab.cmake in config/cmake?

**Comment by kdheepak** [comment]
I can try in some time. I remember that we had to add FindMatlab.cmake for the same reason: getting it to work on Linux.

**Comment by nightlark** [comment]
@kdheepak can you try it with FindMatlab.cmake deleted? It seems to work fine with the default one included with cmake 3.5 on my system.

**Comment by kdheepak** [comment]
I tried that as well and it seemed to work. I'm not able to install it at the moment though (unrelated issues). I don't have any errors in the CMake process.

**Comment by nightlark** [comment]
Okay, that's good. We should probably remove the copy of FindMatlab.cmake.
