### ISSUE TITLE
Logging API to get user messages into the logging system

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#606]
**Is your feature request related to a problem? Please describe.**
The need for more logging 

**Describe the solution you'd like**
a clear function call for getting user messages into the log

This is a feature request to expose the Core API logging calls to the application API and C library.

**Comment by trevorhardy** [comment]
To add some details, when using Python's `logging` package, message sent to `logging.info()` make there way into the HELICS log file but appear to be flushed at times that are inconsistent with the HELICS log messages. This creates confusion in the log file and makes it impossible to understand the order of events as reported by the federate. A native HELICS logging function would allow federate authors to write messages into the HELICS log file that would ensure synchronization with the other HELICS log messages.

```
EV_Controller (131073) (0)::Granted Time=21600
EV_Controller (131073) (0)::exec=21600 allow=21600, value=21301, message=9.22337e+09, minDe=21301 minminDe=21301
EV_Controller (131073) (0)::exec=21600 allow=21600, value=21301, message=9.22337e+09, minDe=21301 minminDe=21301
EV_Controller (131073) (0)::processing cmd time_grant:From (1) Granted Time(21600) to (131073)
EV_Controller (131073) (0)::processing cmd time_grant:From (131074) Granted Time(21600) to (131073)
EV_Controller (131073) (0)::processing cmd time_grant:From (131073) Granted Time(21600) to (131073)
EV_Controller (131073) (0)::processing cmd pub:From (131074) handle(0) size 17 at 21600 to 131073
EV_Controller (131073) (0)::exec=21600 allow=21600, value=21301, message=9.22337e+09, minDe=21301 minminDe=21301
EV_Controller (131073) (0)::receive publication pub:From (131074) handle(0) size 0 at 21600 to 131073
EV_Controller (131073) (0)::processing cmd pub:From (131074) handle(1) size 17 at 21600 to 131073
EV_Controller (131073) (0)::exec=21600 allow=21600, value=21301, message=9.22337e+09, minDe=21301 minminDe=21301
EV_Controller (131073) (0)::receive publication pub:From (131074) handle(1) size 0 at 21600 to 131073
EV_Controller (131073) (0)::processing cmd pub:From (131074) hanEV Controller grantedtime = 21900.0
Total Feeder Load is 2881032.742045034 + 933250.2484611124 j
EV Controller grantedtime = 22200.0
Total Feeder Load is 2892596.679470324 + 936856.727896499 j
EV Controller grantedtime = 22500.0
Total Feeder Load is 2900280.385898214 + 938798.6768005902 j
EV Controller grantedtime = 22800.0
Total Feeder Load is 2913701.088299563 + 943195.156796008 j
dle(2) size 17 at 21600 to 131073
EV_Controller (131073) (0)::exec=21600 allow=21600, value=21301, message=9.22337e+09, minDe=21301 minminDe=21301
EV_Controller (131073) (0)::receive publication pub:From (131074) handle(2) size 0 at 21600 to 131073
EV_Controller (131073) (0)::processing cmd pub:From (131074) handle(3) size 17 at 21600 to 131073
EV_Controller (131073) (0)::exec=21600 allow=21600, value=21301, message=9.22337e+09, minDe=21301 minminDe=21301
```

**Comment by eberleim** [comment]
@10tranr and I have produced a working logging API through the Federate interface to put a message in that Federate's log. Additionally, @10tranr will generate any examples, test cases, and interfaces needed to use this externally. 

@phlptp do we also want the ability to directly interact with the broker log, or is individual Federates adequate? 

current changes are located in HELICS/logging-api-enhancement

**Comment by phlptp** [comment]
How does this interact with the existing logging system?  There might need to be some work to make sure it is thread-safe so it can be used in a multithread context.    Why don't you submit a PR and we can work through some of the potential issues. But I like where it is going, I think it will be a valuable addition.

We will also need a few test cases as part of the test library.
