### ISSUE TITLE
Update licenses & copyrights for GMLC-TDC organization repos

### ISSUE THREAD

**Issue by bpalmintier** [GMLC-TDC/HELICS#623]
This is a generalization of #621 to track consistent updates to our related repositories. See repo list and assignments below. Once the specifics are finalized, we should go through all repos and setup:

1. LICENSE file that matches that in `HELICS`
2. NOTICE file that matches that in `HELICS` (unless otherwise decided)
3. CONTRIBUTORS.md file that lists third-party code and license info that is included in the repository
4. CONTRIBUTING.md file as a guide for making contributions
5. The finalized copyright/license notice added at the top of each code file developed entirely under the projects or from the primary copyright holders:
6.  README.md should have a release section with the license information

List of repos with suggested assignments (update as needed). Please edit and issue a pull request. I (@bpalmintier) will update this check-list once finalized in master branch for each repo:

- [x] HELICS-src ( @phlptp )
- [x] helics-cli ( @kdheepak )
- [x] homebrew-helics ( @kdheepak ) [ARCHIVED-deprecated]
- [x] HELICS-Examples ( @kdheepak / @bpalmintier )
- [x] HELICS-Use-Cases ( @kdheepak )
- [x] HELICS-User_Guide ( @trevorhardy  ) [ARCHIVED]
- [x] HELICS-Tutorial -- Pending keeping around in #622 
- [x] PSLF-wrapper ( @shwethanidd )\[no contributors file as the repo is quite out of date\]
- [x] MATPOWER-wrapper (@Jacobhansens )
- [x] HELICS-FMI ( @phlptp )
- [x] HELICS-BBX (@phlptp)
- [x] helics-ns3 ( @nightlark ) Will need to be GPL v2 license but needs some additional notes
- [x] HELICS-NS3-dev-archive \[ARCHIVED\] replaced by helics-ns3
- [x] HELICS-HLA ( @HimanshuJain17 )
- [x] HELICS-Characterization-Tests ( @gayukrishna )
- [x] helics-builder ( @kdheepak )
- [x] helics-Conda ( @kdheepak )
- [x] helics-buildenv ( @nightlark  )
- [x] helics.jl ( @kdheepak )
- [x] helics.org (@kdheepak )
- [x] mingw-package [Fork should not have organization license structure]
- [x] utilities (@phlptp)
- [x] containers ( @phlptp )
- [x] concurrency ( @phlptp )
- [x] netif ( @nightlark  )
- [x] cmake-helpers ( @phlptp )
- [x] HELICS.nim (@kdheepak)
- [x] pesgm-2019-helics-tutorial (@kdheepak)
- [x] helics_benchmark_results (@phlptp)

**Comment by phlptp** [comment]
just a note on the containers-repo,  my intention with that will be to have it be a bit more general beyond HELICS, so I would be a little hesitant to change the name to something that implies it is specific to HELICS.

**Comment by phlptp** [comment]
```cpp
/*
       Copyright © 2017-2019,
       Battelle Memorial Institute; Lawrence Livermore National Security, LLC; Alliance for Sustainable Energy, LLC.  See the top-level NOTICE for additional details.
All rights reserved.   
SPDX-License-Identifier: BSD-3-Clause
*/
```

Here is the standardized text that should be used as a file header

**Comment by phlptp** [comment]
@kdheepak  @nightlark  can the status of any this be updated?
