### ISSUE TITLE
`external` flag for broker makes non-ZeroMQ cores not work

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/HELICS#634]
**Describe the bug**
Starting the broker with `--external` with a core type other than ZeroMQ causes the broker to not work (federates are unable to connect).

**What is the expected behavior?**
The other core types should continue working when given `--external` (they don't seem to need it, so it should either be ignored or it should be removed from the help message of non-ZMQ cores and give an error/warning when used).

**Environment (please complete the following information):**
 - HELICS version: 2.0.0 https://github.com/GMLC-TDC/HELICS-src/commit/42cff6f8fa5f99047a9cae570fe64f8710e2ec8c

**Comment by nightlark** [comment]
This also applies when using --ipv4 (and I imagine --ipv6 as well).

**Comment by phlptp** [comment]
Have you tried this with the UDP broker?

**Comment by nightlark** [comment]
I don't remember. The TCP core definitely wasn't working.

**Comment by phlptp** [comment]
I was able to verify the TCP issue as well, but the UDP core works differently so I wasn't sure if that fails in this context as well.    I will test it soon, but I wondered if you knew.

**Comment by phlptp** [comment]
Ok, @nightlark  can you check again.

**Comment by nightlark** [comment]
I tested the tcp, tcpss, and udp cores; the --external flag no longer breaks any of them.

**Comment by phlptp** [comment]
closed with PR #720
