### ISSUE TITLE
Support `pkg-config`

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#647]
We would need to create a `helics.pc` during the `CMake` process, and in the install step copy it over to the relevant directory (`libdir`, i.e. `/usr/local/lib`)

```
prefix=/usr/local
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib

Name: helics
Description: helics library
Version: 2.0.0
Cflags: -I${includedir}/helics
Libs: -L${libdir} -lhelicsSharedLib
```

If we do this we can get rid of `helics-config`.

**Comment by kdheepak** [comment]
If we do this, other applications can get the cflags and lib flags using `pkg-config`:

<img width="1680" alt="Screen Shot 2019-03-12 at 3 30 54 PM" src="https://user-images.githubusercontent.com/1813121/54237562-e3b00100-44db-11e9-8795-0877a47a24ea.png">

**Comment by phlptp** [comment]
I have seen some other packages do it with a helics.pc.in file and a configure file, so it should be possible.  Though from what I understood the helics-config app was potentially useful to python and some other apps which wouldn't use the pkg-config anyway, as well some configuration information on Windows.

**Comment by phlptp** [comment]
I started on this but I don't think it is going to make it into HELICS 2.1
