### ISSUE TITLE
Automatic Installer generation

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#648]
I think one next step is to have the windows installers (possibly others) automatically generated for the release candidates.  I think we are a good chunk of the way there, but I think we need a few configurations and some testing.  Possibly something we can do with Azure as appveyor seems a little slow.

**Comment by kdheepak** [comment]
I'm already doing it on Travis and Appveyor. I can just add an extra step that builds the installer and we can push the final products to the releases page. 

https://travis-ci.com/GMLC-TDC/helics-conda

https://ci.appveyor.com/project/kdheepak/helics-conda-0bk88

**Comment by phlptp** [comment]
I think it is mostly a matter of making sure we have the correct configurations generated and making a decision on what those configurations should be, then we can make sure those configurations are used on the CI builds and uploaded as appropriate.

For Windows
1. MSVC 2017 x64 Release with C++ Shared Lib
2. MSVC 2017 x86 Release
3. MSVC 2017 x64 Debug

4. MSVC 2015 x64 Release

5. Some build with static system libraries included and just the C shared library and headers

**Comment by phlptp** [comment]
#759 is a step in this direction

**Comment by nightlark** [comment]
Additional tasks related to this for the next minor release:
- [ ] macOS installer
- [ ] macOS, Linux, and Windows shared library archives for x86 and x64

**Comment by nightlark** [comment]
Possibly set up future nightly builds.
