### ISSUE TITLE
Appveyor occasional test failure with messageTime

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#682]
**Describe the bug**
The messageTimer tests occasionally fail on Appveyor and sometimes travis
This has not been replicated on local systems.  

[ RUN      ] messageTimer_tests.basic_test
C:\projects\helics-src\tests\helics\core\MessageTimerTests.cpp(34): error: Value of: M.action () == CMD_PROTOCOL
  Actual: false
Expected: true
[  FAILED  ] messageTimer_tests.basic_test (805 ms)
[----------] 1 test from messageTimer_tests (805 ms total)

**Comment by phlptp** [comment]
@nightlark can you trigger a bunch of appveyor builds(10) on the message_timer_fixes branch.  I want to see if the fixes did anything

**Comment by nightlark** [comment]
Several builds are queued for that branch now.

**Comment by phlptp** [comment]
Well at least the segmentation or stack corruption errors  seems to be resolved.  Still not entirely clear why the failures are occurring but they don't seem to be resolved yet.

**Comment by phlptp** [comment]
@nightlark can you trigger the set of builds again,  at least 10 tries on appveyor.

**Comment by nightlark** [comment]
@phlptp builds are queued

**Comment by phlptp** [comment]
Obviously based on the past few builds, Some issues were fixed with PR #704, but the issue has not been resolved yet.

**Comment by phlptp** [comment]
I have not seen this error in the previous number of builds.  If it comes up again we will reopen
