### ISSUE TITLE
Diverse methods of getting inputs

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#702]
**Is your feature request related to a problem? Please describe.**
For large numbers of subscriptions, pulling down the latest value is complicated by the limitation of only collecting one value at a time and doing so by data type.

**Describe the solution you'd like**
Two requests:

1. A method of pulling down all values regardless of data type.
2. A method for pulling down all values regardless of data type only if they have changed.

**Describe alternatives you've considered**
The current method of updating the inputs to a federate requires manually iterating over a list of subscription IDs (a large list if the federate has subscribed to a large number of values) and then comparing them to previously stored values to determine if any have changed and trigger execution of some portion of code. Particularly in cases where only a small number of these inputs are expected to change from one time grant to another, this can be time consuming. Though HELICS does have an API to determine if a single subscription has been updated, it also must be called iteratively if all subscriptions need to be evaluated.

**Comment by phlptp** [comment]
Some thoughts.
A general solution would be some notion of the conduit library would support user defined structures of different subscriptions/inputs.  

In a slightly simpler fashion I think a query could be defined that would just get a structure of the current inputs or updated inputs in JSON, that would then require the federate making the query to parse json or a structured text in some fashion and represent numbers as strings which will lose some precision.  

One other option is some sort of object in C which is an iterator to a vector of updates.  
or figuring out how to do the callbacks in the other languages.  

The json queries are pretty straightforward and could be added pretty quickly.  
We should really figure out the callbacks someday.
Conduit is a a bigger task but gives a lot of potential and benefits beyond this particular issues. 

Philip

**Comment by trevorhardy** [comment]
Phil, in looking over the PR that  [addresses this](https://github.com/GMLC-TDC/HELICS/pull/739), it is unclear to me how the input JSONs are used for publishJSON and regsterFromPublication.

```
{
  "pub2" : "things",
  "group1" : {
    "pubA" : 45.7,
    "pubB" : "count"
  },
  "pub1" : 99.9
}
```

Your explanations of the returns on the new queries ("updated_input_indices", "updated_input_names", "updates") all look great.

updated_input_indices -> string "[1;2;3]"
updated_input_names -> string "[pub1;pub2;pub3]"
updates -> JSON:
```
{
   "pub1" : 45.700000000000003,
   "pub2" : 23.100000000000001,
   "pub3" : 19.399999999999999
}
```

or for updates to the local federate:
```
{
   "fed0" :
   {
      "pub2" : 23.100000000000001,
      "pub3" : 19.399999999999999
   },
   "pub1" : 45.700000000000003
}
 
```

**Comment by phlptp** [comment]
The publishJson and register from publicationJson take a string which can be a filename or straight Json string.

They parse the json then extract the data and path and try to find an existing publication that matches and if so publish the data. Currently as string or double though if needed I can probably add more types.

Philip

Philip


---
Sent from Workspace ONE Boxer<https://whatisworkspaceone.com/boxer>

On July 12, 2019 at 11:38:58 AM PDT, Trevor Hardy <notifications@github.com> wrote:

Phil, in looking over the PR that addresses this<https://github.com/GMLC-TDC/HELICS/pull/739>, it is unclear to me how the input JSONs are used for publishJSON and regsterFromPublication.

{
  "pub2" : "things",
  "group1" : {
    "pubA" : 45.7,
    "pubB" : "count"
  },
  "pub1" : 99.9
}


Your explanations of the returns on the new queries ("updated_input_indices", "updated_input_names", "updates") all look great.

updated_input_indices -> string "[1;2;3]"
updated_input_names -> string "[pub1;pub2;pub3]"
updates -> JSON:

{
   "pub1" : 45.700000000000003,
   "pub2" : 23.100000000000001,
   "pub3" : 19.399999999999999
}


or for updates to the local federate:

{
   "fed0" :
   {
      "pub2" : 23.100000000000001,
      "pub3" : 19.399999999999999
   },
   "pub1" : 45.700000000000003
}

**Comment by trevorhardy** [comment]
Oh, I see. Its a way to manually insert data onto the HELICS message bus using JSONs. Is this related to the issue under discussion here or is it just being bundled into the same PR?

**Comment by phlptp** [comment]
It is in support of the ngfast stuff but it uses similar code and I wanted to make them symmetric so that is why they are in the same PR.


Philip


---
Sent from Workspace ONE Boxer<https://whatisworkspaceone.com/boxer>

On July 12, 2019 at 12:02:14 PM PDT, Trevor Hardy <notifications@github.com> wrote:

Oh, I see. Its a way to manually insert data onto the HELICS message bus using JSONs. Is this related to the issue under discussion here or is it just being bundled into the same PR?
