### ISSUE TITLE
More standard IT network behavior

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#716]
**Is your feature request related to a problem? Please describe.**
IT personnel who are working on implementing a multi-site co-simulation have expressed some degree of difficulty in dealing with the way HELICS uses IPs and ports. Configuration or firewalls and proxies is made more challenging by this behavior.

**Describe the solution you'd like**
A more standard use of IPs and ports would reduce the complexity for multiple-site HELICs co-simulations. Additionally, specific documentation on how these kinds of devices should be configured would at least reduce the difficulty of supporting this for IT staff.

**Comment by nightlark** [comment]
The single socket core types might be what they are looking for so that the firewall just needs a single port opened for the broker connections -- the default port for tcpss is 33133, and zmqss uses 23414.

**Comment by trevorhardy** [comment]
PNNL will be testing the tcpss core to see if it will solve our infrastructure problems and also evaluate the message-carrying capacity to make sure it will work for us. Stay tuned for further updates.

**Comment by phlptp** [comment]
If you want some guidance on how that works, let us know.

**Comment by phlptp** [comment]
The benchmarks of that vs the zmq core for the various tests would be interesting

**Comment by trevorhardy** [comment]
Closing out for now as the referenced project has been able to resolve their difficulties using features @phlptp has implemented to support said project.
