### ISSUE TITLE
Install Directions in README only describe build from source

### ISSUE THREAD

**Issue by bpalmintier** [GMLC-TDC/HELICS#732]
The current README file "Install directions" point to build directions by platform. While helpful for those building from scratch, it would be more generally useful to point most users to easier approaches, such as pre-compiled release binaries, homebrew, and the like. Ideally this would include a brief description of each of the various options to help guide which choice for a user, e.g. are MATLAB and Python support included in the Windows Binary? What is preferred way to get running on Mac? Is Conda only for Python? What does it take to get Julia support? Which Linux package managers support HELICS? etc.

**Comment by nightlark** [comment]
Interfaces not included in the main HELICS repo (Julia, nim) should have READMEs that describe or point to instructions on how to get them working rather than trying to do it all here. We should have a list of language interfaces with links to their main repository in the README.

**Comment by phlptp** [comment]
@bpalmintier   can you take a look at the current update since 2.1.1 and let us know if that is sufficient or we need something else?

**Comment by phlptp** [comment]
@bpalmintier some docs were added so I am going to close the issue, if you need something more specific please open a new issue with the details.
