### ISSUE TITLE
HELICS compile with standalone mingw and cygwin on windows

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#751]
**Is your feature request related to a problem? Please describe.**
There are some packages that might use HELICS using a standalone version of mingw on windows or cygwin directly.  This is supported in msys2 environment but the standalone verison of HELICS might require some work yet.  

**Describe the solution you'd like**
verification and possible test of compilation on standalone version of mingw, gcc compiler and possibly cygwin

**Additional context**
Some related discussion in gitter

**Comment by phlptp** [comment]
@nightlark   how hard is to add a travis or azure build for mingw on HELICS.  And when should that be run?  Daily/commit/ develop-master?

**Comment by nightlark** [comment]
Easy if the Windows image has mingw installed, or if mingw can be installed
with chocolatey. At least daily develop and PRs to master.

**Comment by phlptp** [comment]
I got HELICS building on mingw standalone and on cygwin32.  It looks like cygwin64 is impossible at present since ASIO does not support it (io_context so no timers or anything, someday if it is really needed I might be able to strip it out but the TCP and UDP cores would be disabled).  Also helics-config won't build on cygwin32 due to some filesystem support issues on cygwin,

**Comment by phlptp** [comment]
@nightlark  can you add a travis or azure build with mingw on windows to the branch.  Lets make sure it works on the branch, then shortly after shift it so it just runs on the desired situations.

**Comment by nightlark** [comment]
Yea, I’ll try to add one to the Travis builds.

**Comment by phlptp** [comment]
@nightlark did you make any progress on this?

**Comment by nightlark** [comment]
No, I haven’t tried adding it yet — just found info on the problems others have run into with mingw builds on Azure (out of date docs?).

**Comment by phlptp** [comment]
issue addressed in #776
