### ISSUE TITLE
MATLAB extension on Mac breaks with dylib versions

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#763]
```matlab
$ /Applications/MATLAB_R2017b.app/bin/matlab -nodesktop -nosplash -nojvm

                                                              < M A T L A B (R) >
                                                    Copyright 1984-2017 The MathWorks, Inc.
                                                     R2017b (9.3.0.713579) 64-bit (maci64)
                                                              September 14, 2017


For online documentation, see http://www.mathworks.com/support
For product information, visit www.mathworks.com.

>> helicsStartup
Loading HELICS (from /Users/$USER/local/helics-develop/matlab)...
Error using loadlibrary
There was an error loading the library "/Users/$USER/local/helics-develop/matlab/libhelicsSharedLib.dylib"
dlopen(/Users/$USER/local/helics-develop/matlab/libhelicsSharedLib.dylib, 6): image not found

Error in helicsStartup (line 56)
        loadlibrary(GetFullPath(fullfile(helicsLibPath, libraryName)));

Caused by:
    Error using loaddefinedlibrary
    dlopen(/Users/$USER/local/helics-develop/matlab/libhelicsSharedLib.dylib, 6): image not found

>>
```

**Comment by kdheepak** [comment]
The problem is that `libhelicsSharedLib.dylib` points to the wrong file:

```
$ ls
Permissions Size Date Modified Name
drwxr-xr-x     - 31 Jul 15:29  +helics/
.rw-r--r--    72 31 Jul 15:25  generatehelicsMEXFile.m
.rw-r--r--   11k  7 Mar 13:52  GetFullPath.m
drwxr-xr-x     - 31 Jul 15:29  headers/
.rw-r--r--  419k 31 Jul 15:25  helicsMEX.cpp
.rw-r--r--  218k 31 Jul 15:26  helicsMEX.mexmaci64
.rw-r--r--     0  7 Mar 13:52  helicsSharedLib.h
.rw-r--r--  1.5k 10 Jun 10:32  helicsStartup.m
.rw-r--r--   13M 31 Jul 15:25  libhelicsSharedLib.2.1.1.dylib
lrwxr-xr-x    26  3 Aug 14:46  libhelicsSharedLib.dylib -> libhelicsSharedLib.2.dylib
.rw-r--r--     0  7 Mar 13:52  libhelicsSharedLib.h
.rw-r--r--    45  7 Mar 13:52  SwigGet.m
.rw-r--r--   345  7 Mar 13:52  SwigMem.m
.rw-r--r--   827  7 Mar 13:52  SwigRef.m
```

If I run the following:

```
cd /Users/dkrishna/local/helics-develop/matlab/
rm libhelicsSharedLib.dylib
ln -s libhelicsSharedLib.2.1.1.dylib `pwd`/libhelicsSharedLib.dylib
```

Everything works as expected:

```
>> helicsStartup
Loading HELICS (from /Users/$USER/local/helics-develop/matlab)...
>> helics.helicsGetVersion()

ans =

    '2.1.1 (07-16-19)'

>>

```

**Comment by bpalmintier** [comment]
This also happens under R2018b and R2019a. As @kdheepak points out the work around is related to fixing the symlink chain for `libhelicsSharedLib.dylib`

**Comment by nightlark** [comment]
This looks like an issue with the matlab interface trying to pick and install copies of individual files instead of using swig_add_library and swig_target_link_libraries like the other swig interfaces.

Does matlab have any compiled files or is it all readable .m files? I think the matlab interface should be trying to use the shared library from the lib folder of the HELICS install prefix instead of having a separate copy that it tries to maintain. If it’s all .m files maybe running helics-config to get the path would work, or a user just needs to make sure the lib folder with helicsSharedLib is in their LD_LIBRARY_PATH environment variables (an install in a standard system path like /usr/local should just work).

**Comment by kdheepak** [comment]
So I think it's just this that needs to be changed:

https://github.com/GMLC-TDC/HELICS/blob/cad21acaac68d25b50e08b185d4fe5a1ae054241/interfaces/matlab/helicsStartup.m#L4-L8

**Comment by kdheepak** [comment]
We still have this issue in the matlab folder. I don't see any `install` associated with the shared library in the `matlab/CMakeLists.txt`, so I'm not sure why this is happening or what is going on.

**Comment by nightlark** [comment]
This will be something to fix in HELICS+ along with setting up a build running matlab CI tests and adding some support for a standalone matlab interface build using an existing HELICS install.

**Comment by kdheepak** [comment]
This just requires a symbolic link to the output of cmake install step,
right?

**Comment by nightlark** [comment]
I think the solution could be getting linking or the rpath settings right when building the matlab extension (or having a copy of HELICS installed in a system folder or other place on the search path for shared libs). A symlink seems similar to making a copy of the shared library -- a hack that shouldn't be needed except on Windows.

**Comment by kdheepak** [comment]
The problem is we add a symlink like so `libhelicsSharedLib.dylib -> libhelicsSharedLib.2.dylib` but `libhelicsSharedLib.2.dylib` does not exist in the `matlab` folder. In the `lib` folder, we have `libhelicsSharedLib.2.dylib -> libhelicsSharedLib.2.4.0.dylib` as well. Shouldn't we add that here too?

**Comment by nightlark** [comment]
I don't think any of those symlinks or files should be in the `matlab` folder.

**Comment by trevorhardy** [comment]
I'm going to close this out as I suspect, based on the dates none of this is relevant anymore under HELICS v3 and our new MATLAB mex.
