### ISSUE TITLE
`ENABLE_SWIG=OFF` should be default

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#765]
Currently `ENABLE_SWIG` is set to `ON`. This requires `swig` to be installed for building the Python interface. Either this should be turned off if it can't find swig, or `ENABLE_SWIG` should default to `OFF`.

**Comment by phlptp** [comment]
I would propose only having this option if BUILD_MATLAB_INTERFACE, BUILD_JAVA_INTERFACE, or BUILD_PYTHON_INTERFACE is enabled and none of the others are.  These are the only cases where this is actually an option, all the others require swig.    The the default could be off for this conditional option.
