### ISSUE TITLE
Add sha256 file to the single zip file

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#810]
**Is your feature request related to a problem? Please describe.**
We need to generate a sha256 file associated with the single file zip so it can be verified by automated package generators.

**Describe the solution you'd like**
this should be done immediately on creation so it needs to be part of the script that generates the original file

**Comment by nightlark** [comment]
Is the sha256 file a separate download? Do you have a link to an example of the file format that the automated package generator is looking for?

**Comment by phlptp** [comment]
It is needed for a lot of package builders for [Example](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-cython/PKGBUILD)

I think the Cmake format is fine.  The main purpose is as a reference to use when creating the build packages in the future and if anyone wants to verify the download.  And to make it legitimate I think the SHA code has to be generated at the point of creation and before upload.  

Is this something that can be added to #812 ?

**Comment by nightlark** [comment]
I'll add it in a separate PR, I want to see if I can work out a way to get the hash for other uploaded assets to also be included in the file.
