### ISSUE TITLE
Figure out how to use swig to generate the included documentation for the interface functions

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#814]
**Is your feature request related to a problem? Please describe.**
currently the interface functions generated by cmake have little to no documentation.  There seems to be some facilities in swig to generate this but we are not currently making use of them.  

**Describe the solution you'd like**
We should have some in language documentation facilities for the different language API's ideally automatically generated.

**Comment by nightlark** [comment]
It looks like support for translating Doxygen comments to Java and Python was added in SWIG 4. I didn't see this feature mentioned in the SWIG 3 documentation, and other results for documentation features were for SWIG 1.x versions.

http://www.swig.org/Doc4.0/SWIGDocumentation.html#Doxygen

**Comment by phlptp** [comment]
completed in #883
