### ISSUE TITLE
Travis Xcode 8.3 build

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#839]
The Xcode 8.3 build is failing on [Travis](https://travis-ci.com/GMLC-TDC/HELICS/jobs/241999568).

We either need to fix it or determine the cause of the issue.    If support is old enough we may want to move to 9.X and  mention dropping tested support for 8.3 in HELICS 2.3.

**Comment by nightlark** [comment]
It looks like it has started failing on the Homebrew install step 5 days ago (https://travis-ci.com/GMLC-TDC/HELICS/jobs/241055580#L464-L465) -- now it is trying to compile gcc from source, whereas before it downloaded a compiled version.

Before that, it looks like the first failure was September 27 (https://travis-ci.com/GMLC-TDC/HELICS/jobs/239906917), but I'm not seeing what the error is since the day before it worked (https://travis-ci.com/GMLC-TDC/HELICS/jobs/239907834). This build was also on the same commit. 

Moving to XCode 9.x would mean that macOS 10.12 or newer is needed (10.11 was released 4 years ago and there are probably less than 10% of macOS users still on it).

**Comment by phlptp** [comment]
Technically I don't think we have changed anything that would impact Xcode 7.3 yet either, but the real question is how much time would it take to fix the 8.3 travis build?    Is there an alternative (Azure)  and do we think anyone cares about 8.3 any more?    HELICS 3.0 will require at least 10.X  so it isn't that much of leap to just state that 9.X is the minimum tested though we think older ones still work.  Especially if it will be a pain to get 8.3 working again.    Thoughts?

**Comment by nightlark** [comment]
I don't think getting 8.3 working on Travis again will happen. Getting around homebrew compiling gcc would be a pain, and I haven't been able to figure out from the older logs why it is failing.

Azure doesn't have the homebrew problems, maybe because macOS 10.13 is their oldest version.

**Comment by phlptp** [comment]
ok,  will 9.X have any of the same issues?

**Comment by nightlark** [comment]
On Travis:
- XCode 9.2 on macOS 10.12 also compiles gcc from source and times out
- XCode 9.4 on macOS 10.13 HELICS compiles w/o errors

**Comment by phlptp** [comment]
do we have any idea why it is compiling gcc?,  that seems odd since we are purposely using the clang compiler that comes with xcode?

**Comment by nightlark** [comment]
I'd guess that one or more homebrew packages get compiled with gcc, and that the homebrew maintainers have decided that macOS 10.12 is getting too old to maintain precompiled packages for.

**Comment by phlptp** [comment]
what homebrew packages are we installing?

**Comment by nightlark** [comment]
https://github.com/GMLC-TDC/HELICS/blob/master/.ci/Brewfile.travis

**Comment by phlptp** [comment]
well on that list we can definitely drop swig,  and we can probably drop boost as well, I don't imagine the IPC core on old macs will be that useful.  not sure what pcre and ccache are doing?    We need cmake,  but if we had to zeromq is optional.

**Comment by nightlark** [comment]
pcre is used by swig. I have builds running that drop most of them one at a time. Down to just cmake and zeromq. ccache looks like it is required, otherwise it ccache needs to be disabled for the Linux builds too.

**Comment by nightlark** [comment]
For macOS versions tested we might want to follow the most recent 3 versions Homebrew supports for compiled packages. XCode major versions seem to follow the macOS releases, except they tend to support the previous macOS release as well (XCode 9 came out around macOS 10.13, but also can be installed on 10.12).

**Comment by phlptp** [comment]
What would recommend as a policy for our XCode support?  HELICS 3.0 will probably need to be at least XCode 10,  but outside of that change what should our policy be on tested XCode support?  I am ok bumping it up but we should have some sort of specified policy beyond when travis breaks our tests.

**Comment by nightlark** [comment]
I think the 3 most recent XCode releases, with the time between a major XCode release and the corresponding macOS release being a 2-3mo window for updating the CI builds.
