### ISSUE TITLE
freebsd support

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#840]
support building on Freebsd.  

Looks like there are two main things preventing this yet.  
The use of the Filesystem library, and the NetIF code doesn't seem to work on FreeBSD yet.  

@kdheepak  how were you testing this?

**Comment by kdheepak** [comment]
Using [HELICSBuilder](https://github.com/GMLC-TDC/HELICSBuilder). All you need to do is change the .travis.yml file to include [the FreeBSD target](https://github.com/GMLC-TDC/HELICSBuilder/blob/5a8e8a7754ebbc8f6a8c6237bf3860f497734962/.travis.yml#L29) and check the Travis logs.

**Comment by nightlark** [comment]
@phlptp can you test https://github.com/GMLC-TDC/netif on your TrueOS system? I made changes for FreeBSD support, but there different variants of BSD use different names for macros and header files.

**Comment by phlptp** [comment]
Once I figured out how to enable the tests it build and the tests passed
