### ISSUE TITLE
Add `atexit` callback to helicsCloseLibrary in language bindings

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#858]
I ran the same code in Julia and Python. The code creates a value federate without starting a broker. HELICS errors as expected with a registration failure error.

In Julia, when the error occurs, the remaining lines in the file are not executed, and the process exits. The error code is `1` for the process.

In Python, when the error occurs, the remaining lines in the file are not executed as expected, but when the process tries to exit it just hangs. The user must then run `Ctrl+C` to terminate the process. The error code is `SIGINT(2)` for the `Ctrl+C` and the error code of the process is lost.

![Screen Shot 2019-10-25 at 2 02 02 PM](https://user-images.githubusercontent.com/1813121/67601089-c6f5d000-f730-11e9-9275-b07da3b4e4df.png)

See screenshot for example of this.

In Julia, I added [one line](https://github.com/GMLC-TDC/HELICS.jl/commit/d590fa548710361e00d6f614a8ed63aecb5b485f) that adds `helicsCloseLibrary` as a callback when the process exits, using `atexit` and that provides a nicer user experience during these errors.

**Comment by kdheepak** [comment]
For Python, this is the code we should generate.

```python
import atexit
import helics

...

atexit.register(helics.helicsCloseLibrary())
```

**Comment by phlptp** [comment]
how and where do we generate it so it gets called when users load the library?
