### ISSUE TITLE
Fix integration link with HELICS-Examples for HELICS 2.3

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#902]
**Describe the bug**
what is the current behavior
The HELICS-Examples integrated build is currently failing

**What is the expected behavior?**
 What is the motivation / use case for changing the behavior?
It should pass

**Comment by nightlark** [comment]
This one needs some changes to the CI options in https://github.com/GMLC-TDC/HELICS-Examples/pull/26 to pass. Then it’s just merging it up to the master branch.

**Comment by phlptp** [comment]
This has been resolved with the update to HELICS-Examples
