### ISSUE TITLE
Azure pipelines showing as never built on master

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#908]
The Azure pipelines badge is showing as never built on the master branch.  We either need to get it to built and passing or remove the badge.

**Comment by nightlark** [comment]
Odd, it seems to be building every other branch and PR. I manually queued a build.

**Comment by phlptp** [comment]
Do we have any idea if this will build properly on future updates to master?

**Comment by nightlark** [comment]
The other repositories using azure pipelines are building on updates to master. I don't know why this one didn't trigger a build. Maybe brief downtime or service issue?

**Comment by phlptp** [comment]
This will be closed if the next release builds the azure on master appropriately.

**Comment by phlptp** [comment]
Looks like the recent commit to master worked so this can be closed.
