### ISSUE TITLE
Missing headers on install for just C shared library

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#909]
**Describe the bug**
Some important headers like "helics_enums.h" are missing in the install when doing an install with just the C shared library.   They are included when the C++ shared library is installed as well.  

**What is the expected behavior?**
 What is the motivation / use case for changing the behavior? 
These headers need to be included if any headers are used.  

**To Reproduce**
an install with just the C++ shared libraries turned off.

**Comment by phlptp** [comment]
We can debate this but it might warrant a 2.3.1  sooner rather than later.

**Comment by kdheepak** [comment]
I'd prefer a 2.3.1 release too.
