### ISSUE TITLE
`pkg-config` and `helics-config` should return useful results when used to include headers for `helicsSharedLib`

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#914]
Both `pkg-config` and `helics-config` don't give useful results for `--include`.

```
$ pkg-config --cflags helicsSharedLib
-I/Users/USER/local/helics-develop/include
```

and 

```
$ helics-config --includes
"/Users/USER/local/helics-develop/include"
```

I think they should return the following:

```
-I/Users/USER/local/helics-develop/include/helics/ -I/Users/USER/local/helics-develop/include/helics/shared_api_library
```

Also, `helics-config` always returns a double quoted string for `--libs`, `--includes`, `--prefix`, `--bin` and `--install` . It would be nice to not have the double quotes.

**Comment by phlptp** [comment]
Which folder(s) we include as the include director(y|ies) can be discussed but for the moment changing it would be a breaking change.  I want to do a thorough review for HELICS 3.0 to make sure we are following best practices for header locations for all 3 libraries.  But for the time being they are where they are.  

At least for the C++ shared library I would think the includes as <helics/XXX.hpp> for the main headers would be appropriate.

**Comment by phlptp** [comment]
As far as helics-config goes,  I would be happy to get rid of it in HELICS 3.0 if pkg-config has the same functionality, and happy to review any changes you think would make it more useful, but I don't think we can change the primary include paths without it being a breaking change.

**Comment by nightlark** [comment]
Based on usage for a quick survey of packages installed on LC (boost, jsoncpp, cereal, llvm, antlr, theora, SDL) it looks like having all of the headers in a subfolder is fine. I haven't (yet) found any examples of a C++ library that includes a C interface as part of the standard install to see if they use the same subfolder or separate subfolders.

The one bit that seems to differ is when writing C++ including the subfolder name before the main header file <helics/XXX.hpp> seems to be more common than in C (examples for C libraries), and for --cflags pkg-config tends to return an include path with the subfolder at the end (e.g. "/usr/include/helics").

**Comment by kdheepak** [comment]
I think we shouldn't change `helics-config` but maybe `pkg-config --cflags helicsSharedLib` can be changed to be as above?

**Comment by phlptp** [comment]
This issue is on hold for the time being.  It is expected in HELICS 3.0 this will be updated significantly and helics-config probably removed.  But it is unlikely much will be done until then.
