### ISSUE TITLE
The clang-format action doesn't work with PRs from forks

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/HELICS#971]
**Describe the bug**
The clang-format action doesn't work with PRs from forks.

**What is the expected behavior?**
The format action should not fail. Either don't run if the PR originates from a fork, or serve as an indicator that formatting isn't right (probably should provide some convenient way to get the needed formatting changes in before using this option).

**Comment by phlptp** [comment]
Can this be closed?

**Comment by nightlark** [comment]
Oh, yes. It looks like the PR that disabled them also confirms that the change works.
