### ISSUE TITLE
Proposed documentation structure

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#983]
@phlptp mentioned that @kdheepak would probably be in charge of the documentation so I wanted to share what I've thought of so far in how things could be restructured. All feedback is obviously welcome.

My thought is that the readthedocs pages could be re-organized as follows:

- Homepage - General description of co-simulation with a short paragraph discussing the following. This is the sales pitch for co-simulation with HELICS.
  - Quick overview of HELICS (maybe something like what we already have on our "Introduction" or "User Guide" pages
  - Quick overview of motivation and goals of HELICS
  - Quick overview of supported platforms and languages
  - Funding statement
- Getting Started
  - Installation Guide - More or less the existing installation guide.
  - User Guide - Appropriate combination of the existing "User Guide" pages and the "Introduction" pages
- Developer Reference
  - Developer Guide - More or less the existing Developer Guide
  - API reference pages - See [issue #934](https://github.com/GMLC-TDC/HELICS/issues/934) for details
  - Style Guide - More or less existing Style Guide
  - CI Guide - Reworked version of the [readthedocs CI information](https://helics.readthedocs.io/en/latest/developer-guide/continuous-integration.html)
- Support
  - Description of primary support mechanisms
  - Links to 
    - Gitter channel
    - GitHub Issues page

There is lots of good information on the Github README.md home page that we should in some way coordinate with this information. Maybe the readthedocs and GitHub home pages end up identical?

**Comment by nightlark** [comment]
I've been thinking about the homepages (there's probably a whole discussion that could be had about those), but two of the main questions that I think apply to most pages/sections are 1) who is the audience and 2) what information do they care about. Some of the existing docs feel like they're trying to cater to everyone, where writing pages/docs for a narrower audience could make them more effective.

**Comment by trevorhardy** [comment]
@nightlark, could you point me towards some examples that you think are too broad. 

I agree that not thinking about the audience can lead to overly broad documents that are not useful enough to anybody. We might be able to slice these up and move their constituent parts to appropriate sections of the documentation

**Comment by trevorhardy** [comment]
FYI, preview of the restructured documentation (which is still being developed) can be found here: [https://docs.helics.org/en/v3userguide/user-guide/index.html](https://docs.helics.org/en/v3userguide/user-guide/index.html)

**Comment by trevorhardy** [comment]
The latest ["v3userguide" build of the documentation](https://docs.helics.org/en/v3userguide/user-guide/index.html) is looking more or less like I think it should. That is, the structure is the way I was thinking it should be but there are a lot of content holes to fill. Let me know if you have any suggestions comments.

**Comment by trevorhardy** [comment]
Seeing no further comments on this; I'm going to close the issue for now and consider the current structure "good enough" for now.
