### ISSUE TITLE
Python 3.6 cannot import helics module

### ISSUE THREAD

**Issue by ArtRie** [GMLC-TDC/HELICS#999]
**Bug Description**
Installed python 3.6 and then installed helics module successfully (helics-2.2.1)
Cannot import helics module while using python 3.6 
Can do it with python 3.7 (re-installing helics)

> C:\Users>pip install helics
> Requirement already satisfied: helics in c:\users\appdata\local\programs\python\python36\lib\site-packages (2.2.1)
> Requirement already satisfied: future in c:\users\appdata\local\programs\python\python36\lib\site-packages (from helics) (0.18.2)
> Requirement already satisfied: six in c:\users\appdata\local\programs\python\python36\lib\site-packages (from helics) (1.13.0)
> 
> C:\Users\>python
> Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import helics
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\helics\__init__.py", line 13, in <module>
>     from . import _helics
> ImportError: cannot import name '_helics'
> 

**What is the expected behavior?**
helics module can be imported and used in python 3.6

**To Reproduce**
Install and import helics module while using python 3.6

**Environment (please complete the following information):**
 - Operating System: Windows
 - Language Extension: Python 3.6.8
 - HELICS version: 2.2.1

**Comment by kdheepak** [comment]
`pip install helics` does not work (yet). Please use `conda install -c gmlc-tdc helics`.

**Comment by ArtRie** [comment]
Did help with installation. Still cannot import helics.

**Comment by kdheepak** [comment]
Can you post the stacktrace you get when you try `import helics` after installing with `conda`?

**Comment by ArtRie** [comment]
(python36) PS C:\> conda install -c gmlc-tdc helics
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

(python36) PS C:\> python
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import helics
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\python36\lib\site-packages\helics\__init__.py", line 13, in <module>
    from . import _helics
ImportError: cannot import name '_helics'
>>>

**Comment by kdheepak** [comment]
Did you make sure you did `pip uninstall helics`? I'm regenerating the builds for v2.3.1 to see if anything fails for Windows Python 3.6 64bit.

> Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32

I'll try to recreate the similar environment on my Windows virtual machine and see what happens.

**Comment by kdheepak** [comment]
Python 3.6 [32 bit](https://travis-ci.com/GMLC-TDC/helics-conda/jobs/272977092#L1626) and [64 bit](https://travis-ci.com/GMLC-TDC/helics-conda/jobs/272977093#L1624) builds were both successful and we were able to run the test for [32 bit](https://travis-ci.com/GMLC-TDC/helics-conda/jobs/272977092#L1543) and [64 bit](https://travis-ci.com/GMLC-TDC/helics-conda/jobs/272977093#L1541) successfully on Travis. 

These new builds were also uploaded to [anaconda.org](https://anaconda.org/gmlc-tdc/helics/files). So you should try the following again:

```
pip uninstall helics
conda uninstall helics
conda install -c gmlc-tdc helics
```

Let us know if that still doesn't work.

**Comment by ArtRie** [comment]
This worked. Thank you!
